///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConsumerPagesAbstract.LyndaHeaderFooterPage2
{
    /// <summary>
    /// The class representing the HeaderRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    [RepositoryFolder("dfc29b64-9e01-4cde-a284-750ba31c725c")]
    public partial class HeaderRepo : RepoGenBaseFolder
    {
        static HeaderRepo instance = new HeaderRepo();
        HeaderRepoFolders.DOMAppFolder _dom;

        /// <summary>
        /// Gets the singleton class instance representing the HeaderRepo element repository.
        /// </summary>
        [RepositoryFolder("dfc29b64-9e01-4cde-a284-750ba31c725c")]
        public static HeaderRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public HeaderRepo() 
            : base("HeaderRepo", "", null, 30000, false, "dfc29b64-9e01-4cde-a284-750ba31c725c", "./RepositoryImages\\HeaderRepodfc29b64.rximgres")
        {
            _dom = new HeaderRepoFolders.DOMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("c7784686-0c44-4c60-af7f-7d76554d7088")]
        public virtual HeaderRepoFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    public partial class HeaderRepoFolders
    {
        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("c7784686-0c44-4c60-af7f-7d76554d7088")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _lyndaimageInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "c7784686-0c44-4c60-af7f-7d76554d7088", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "c7784686-0c44-4c60-af7f-7d76554d7088");
                _lyndaimageInfo = new RepoItemInfo(this, "LyndaImage", "body/div[1]/div[@id='topHeader']/div[3]/div[2]/a/img[@title='lynda.com']", 30000, null, "9b080be3-8a5a-4ee4-9666-998e8cb121cf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c7784686-0c44-4c60-af7f-7d76554d7088")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c7784686-0c44-4c60-af7f-7d76554d7088")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LyndaImage item.
            /// </summary>
            [RepositoryItem("9b080be3-8a5a-4ee4-9666-998e8cb121cf")]
            public virtual Ranorex.ImgTag LyndaImage
            {
                get
                {
                    return _lyndaimageInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The LyndaImage item info.
            /// </summary>
            [RepositoryItemInfo("9b080be3-8a5a-4ee4-9666-998e8cb121cf")]
            public virtual RepoItemInfo LyndaImageInfo
            {
                get
                {
                    return _lyndaimageInfo;
                }
            }
        }

    }
}