///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Browsers.ChromeBrowser
{
    /// <summary>
    /// The class representing the Chrome element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.2.3"), RepositoryFolder("cf5abfec-c870-4e9f-abf2-d23d77ae15ed")]
    public partial class Chrome : RepoGenBaseFolder
    {
        static Chrome instance = new Chrome();

        /// <summary>
        /// Gets the singleton class instance representing the Chrome element repository.
        /// </summary>
        [RepositoryFolder("cf5abfec-c870-4e9f-abf2-d23d77ae15ed")]
        public static Chrome Instance
        {
            get { return instance; }
        }

        ChromeFolders.DOMAppFolder _dom;
        ChromeFolders.FormAppFolder _form;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Chrome() 
            : base("Chrome", "", null, 30000, false)
        {
            _dom = new ChromeFolders.DOMAppFolder(this);
            _form = new ChromeFolders.FormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("f5109710-53f2-48e2-b62b-d7ae1fcd5a4a")]
        public virtual ChromeFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }

        /// <summary>
        /// The Form folder.
        /// </summary>
        [RepositoryFolder("170f8a50-6744-42ec-a564-43e5d976d113")]
        public virtual ChromeFolders.FormAppFolder Form
        {
            get { return _form; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class ChromeFolders
    {
        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("f5109710-53f2-48e2-b62b-d7ae1fcd5a4a")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _webpageInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "f5109710-53f2-48e2-b62b-d7ae1fcd5a4a")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "f5109710-53f2-48e2-b62b-d7ae1fcd5a4a");
                _webpageInfo = new RepoItemInfo(this, "WebPage", "", 30000, null, "a04f60ff-c95b-4a04-ae99-3e7cd867c805");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f5109710-53f2-48e2-b62b-d7ae1fcd5a4a")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f5109710-53f2-48e2-b62b-d7ae1fcd5a4a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WebPage item.
            /// </summary>
            [RepositoryItem("a04f60ff-c95b-4a04-ae99-3e7cd867c805")]
            public virtual Ranorex.WebDocument WebPage
            {
                get
                {
                    return _webpageInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The WebPage item info.
            /// </summary>
            [RepositoryItemInfo("a04f60ff-c95b-4a04-ae99-3e7cd867c805")]
            public virtual RepoItemInfo WebPageInfo
            {
                get
                {
                    return _webpageInfo;
                }
            }
        }

        /// <summary>
        /// The FormAppFolder folder.
        /// </summary>
        [RepositoryFolder("170f8a50-6744-42ec-a564-43e5d976d113")]
        public partial class FormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _navigateeditboxInfo;
            RepoItemInfo _titlebarInfo;

            /// <summary>
            /// Creates a new Form  folder.
            /// </summary>
            public FormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form", "/form[@class='Chrome_WidgetWin_0']", parentFolder, 30000, true, "170f8a50-6744-42ec-a564-43e5d976d113")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "170f8a50-6744-42ec-a564-43e5d976d113");
                _navigateeditboxInfo = new RepoItemInfo(this, "NavigateEditBox", "element[@class='Chrome_OmniboxView']/text", 30000, null, "02c46c0c-e463-4e08-99b2-af7709493f70");
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "container/toolbar[@accessiblename='Google Chrome Toolbar']", 30000, null, "40ea7bc6-06c5-4830-be2f-398e7a7f9ae1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("170f8a50-6744-42ec-a564-43e5d976d113")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("170f8a50-6744-42ec-a564-43e5d976d113")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NavigateEditBox item.
            /// </summary>
            [RepositoryItem("02c46c0c-e463-4e08-99b2-af7709493f70")]
            public virtual Ranorex.Text NavigateEditBox
            {
                get
                {
                    return _navigateeditboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NavigateEditBox item info.
            /// </summary>
            [RepositoryItemInfo("02c46c0c-e463-4e08-99b2-af7709493f70")]
            public virtual RepoItemInfo NavigateEditBoxInfo
            {
                get
                {
                    return _navigateeditboxInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("40ea7bc6-06c5-4830-be2f-398e7a7f9ae1")]
            public virtual Ranorex.ToolBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.ToolBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("40ea7bc6-06c5-4830-be2f-398e7a7f9ae1")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }
        }

    }
}