///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Tests.General.Tests.ConsumerReg
{
    /// <summary>
    /// The class representing the ConsumerRegRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    [RepositoryFolder("c01e8542-268c-458b-a9b3-363285851754")]
    public partial class ConsumerRegRepo : RepoGenBaseFolder
    {
        static ConsumerRegRepo instance = new ConsumerRegRepo();
        ConsumerRegRepoFolders.FormAppFolder _form;
        ConsumerRegRepoFolders.DOMAppFolder _dom;
        ConsumerRegRepoFolders.MemberPageFolder _memberpage;
        ConsumerRegRepoFolders.RegStep1PageFolder _regstep1page;
        ConsumerRegRepoFolders.RegStep2PageFolder _regstep2page;
        ConsumerRegRepoFolders.RegConfirmPageFolder _regconfirmpage;

        /// <summary>
        /// Gets the singleton class instance representing the ConsumerRegRepo element repository.
        /// </summary>
        [RepositoryFolder("c01e8542-268c-458b-a9b3-363285851754")]
        public static ConsumerRegRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public ConsumerRegRepo() 
            : base("ConsumerRegRepo", "", null, 30000, false, "c01e8542-268c-458b-a9b3-363285851754", "./RepositoryImages\\ConsumerRegRepoc01e8542.rximgres")
        {
            _form = new ConsumerRegRepoFolders.FormAppFolder(this);
            _dom = new ConsumerRegRepoFolders.DOMAppFolder(this);
            _memberpage = new ConsumerRegRepoFolders.MemberPageFolder(this);
            _regstep1page = new ConsumerRegRepoFolders.RegStep1PageFolder(this);
            _regstep2page = new ConsumerRegRepoFolders.RegStep2PageFolder(this);
            _regconfirmpage = new ConsumerRegRepoFolders.RegConfirmPageFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Form folder.
        /// </summary>
        [RepositoryFolder("77812b61-8c32-44da-946d-ebfadb4bcaaf")]
        public virtual ConsumerRegRepoFolders.FormAppFolder Form
        {
            get { return _form; }
        }

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("68370cb0-1a1c-445e-ac5d-9cbc309c9932")]
        public virtual ConsumerRegRepoFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }

        /// <summary>
        /// The MemberPage folder.
        /// </summary>
        [RepositoryFolder("a0cedce3-e83e-4a04-aed7-c772fef1be1d")]
        public virtual ConsumerRegRepoFolders.MemberPageFolder MemberPage
        {
            get { return _memberpage; }
        }

        /// <summary>
        /// The RegStep1Page folder.
        /// </summary>
        [RepositoryFolder("fbbf1378-7a58-406e-863a-dbdd7d7ee89f")]
        public virtual ConsumerRegRepoFolders.RegStep1PageFolder RegStep1Page
        {
            get { return _regstep1page; }
        }

        /// <summary>
        /// The RegStep2Page folder.
        /// </summary>
        [RepositoryFolder("44b91685-e20e-4c7e-848d-fe9a0957bbe9")]
        public virtual ConsumerRegRepoFolders.RegStep2PageFolder RegStep2Page
        {
            get { return _regstep2page; }
        }

        /// <summary>
        /// The RegConfirmPage folder.
        /// </summary>
        [RepositoryFolder("ec36dfd4-5128-4edd-9022-24b4b099a3b4")]
        public virtual ConsumerRegRepoFolders.RegConfirmPageFolder RegConfirmPage
        {
            get { return _regconfirmpage; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    public partial class ConsumerRegRepoFolders
    {
        /// <summary>
        /// The FormAppFolder folder.
        /// </summary>
        [RepositoryFolder("77812b61-8c32-44da-946d-ebfadb4bcaaf")]
        public partial class FormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _navigateeditboxInfo;

            /// <summary>
            /// Creates a new Form  folder.
            /// </summary>
            public FormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form", "/form", parentFolder, 30000, true, "77812b61-8c32-44da-946d-ebfadb4bcaaf", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "77812b61-8c32-44da-946d-ebfadb4bcaaf");
                _navigateeditboxInfo = new RepoItemInfo(this, "NavigateEditBox", "element[@class='WorkerW']/container/element[@controlid='41477']/text[@class='Edit']", 30000, null, "122d31d8-85c8-4e64-a222-eb8d267ab3fd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("77812b61-8c32-44da-946d-ebfadb4bcaaf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("77812b61-8c32-44da-946d-ebfadb4bcaaf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NavigateEditBox item.
            /// </summary>
            [RepositoryItem("122d31d8-85c8-4e64-a222-eb8d267ab3fd")]
            public virtual Ranorex.Text NavigateEditBox
            {
                get
                {
                    return _navigateeditboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NavigateEditBox item info.
            /// </summary>
            [RepositoryItemInfo("122d31d8-85c8-4e64-a222-eb8d267ab3fd")]
            public virtual RepoItemInfo NavigateEditBoxInfo
            {
                get
                {
                    return _navigateeditboxInfo;
                }
            }
        }

        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("68370cb0-1a1c-445e-ac5d-9cbc309c9932")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _webpageInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "68370cb0-1a1c-445e-ac5d-9cbc309c9932", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "68370cb0-1a1c-445e-ac5d-9cbc309c9932");
                _webpageInfo = new RepoItemInfo(this, "WebPage", "", 30000, null, "6ef9fa63-c5d7-4561-89b4-db4ce0f4490b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("68370cb0-1a1c-445e-ac5d-9cbc309c9932")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("68370cb0-1a1c-445e-ac5d-9cbc309c9932")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WebPage item.
            /// </summary>
            [RepositoryItem("6ef9fa63-c5d7-4561-89b4-db4ce0f4490b")]
            public virtual Ranorex.WebDocument WebPage
            {
                get
                {
                    return _webpageInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The WebPage item info.
            /// </summary>
            [RepositoryItemInfo("6ef9fa63-c5d7-4561-89b4-db4ce0f4490b")]
            public virtual RepoItemInfo WebPageInfo
            {
                get
                {
                    return _webpageInfo;
                }
            }
        }

        /// <summary>
        /// The MemberPageFolder folder.
        /// </summary>
        [RepositoryFolder("a0cedce3-e83e-4a04-aed7-c772fef1be1d")]
        public partial class MemberPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _subscribelinkInfo;

            /// <summary>
            /// Creates a new MemberPage  folder.
            /// </summary>
            public MemberPageFolder(RepoGenBaseFolder parentFolder) :
                    base("MemberPage", "", parentFolder, 0, false, "a0cedce3-e83e-4a04-aed7-c772fef1be1d", "")
            {
                _subscribelinkInfo = new RepoItemInfo(this, "SubscribeLink", "/dom/body/div[@id='eyebrow']/div[1]/ul/li[2]/a[@innertext='subscribe']", 30000, null, "050b24e0-9350-46d6-96b9-e8eda1c76539");
            }

            /// <summary>
            /// The SubscribeLink item.
            /// </summary>
            [RepositoryItem("050b24e0-9350-46d6-96b9-e8eda1c76539")]
            public virtual Ranorex.ATag SubscribeLink
            {
                get
                {
                    return _subscribelinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SubscribeLink item info.
            /// </summary>
            [RepositoryItemInfo("050b24e0-9350-46d6-96b9-e8eda1c76539")]
            public virtual RepoItemInfo SubscribeLinkInfo
            {
                get
                {
                    return _subscribelinkInfo;
                }
            }
        }

        /// <summary>
        /// The RegStep1PageFolder folder.
        /// </summary>
        [RepositoryFolder("fbbf1378-7a58-406e-863a-dbdd7d7ee89f")]
        public partial class RegStep1PageFolder : RepoGenBaseFolder
        {
            ConsumerRegRepoFolders.AccountInfoFolder _accountinfo;
            ConsumerRegRepoFolders.SignMeUpFolder _signmeup;
            RepoItemInfo _monthlypremiumradioInfo;
            RepoItemInfo _continuebuttonInfo;

            /// <summary>
            /// Creates a new RegStep1Page  folder.
            /// </summary>
            public RegStep1PageFolder(RepoGenBaseFolder parentFolder) :
                    base("RegStep1Page", "", parentFolder, 0, false, "fbbf1378-7a58-406e-863a-dbdd7d7ee89f", "")
            {
                _accountinfo = new ConsumerRegRepoFolders.AccountInfoFolder(parentFolder);
                _signmeup = new ConsumerRegRepoFolders.SignMeUpFolder(parentFolder);
                _monthlypremiumradioInfo = new RepoItemInfo(this, "MonthlyPremiumRadio", "/dom/body/div[1]/div[2]/form/table/tbody/tr[@id='row1008']/td[1]/input[@id='subChoice_1008']", 30000, null, "5d1e1737-2497-4545-a68d-c32c0696ce87");
                _continuebuttonInfo = new RepoItemInfo(this, "ContinueButton", "/dom/body/div[1]/div[2]/form/fieldset/div[1]/table/tbody/tr[8]/td[2]/input[@id='btnContinue']", 30000, null, "4b876dec-f6fd-4f27-859d-3b4610956b08");
            }

            /// <summary>
            /// The MonthlyPremiumRadio item.
            /// </summary>
            [RepositoryItem("5d1e1737-2497-4545-a68d-c32c0696ce87")]
            public virtual Ranorex.InputTag MonthlyPremiumRadio
            {
                get
                {
                    return _monthlypremiumradioInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The MonthlyPremiumRadio item info.
            /// </summary>
            [RepositoryItemInfo("5d1e1737-2497-4545-a68d-c32c0696ce87")]
            public virtual RepoItemInfo MonthlyPremiumRadioInfo
            {
                get
                {
                    return _monthlypremiumradioInfo;
                }
            }

            /// <summary>
            /// The ContinueButton item.
            /// </summary>
            [RepositoryItem("4b876dec-f6fd-4f27-859d-3b4610956b08")]
            public virtual Ranorex.InputTag ContinueButton
            {
                get
                {
                    return _continuebuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ContinueButton item info.
            /// </summary>
            [RepositoryItemInfo("4b876dec-f6fd-4f27-859d-3b4610956b08")]
            public virtual RepoItemInfo ContinueButtonInfo
            {
                get
                {
                    return _continuebuttonInfo;
                }
            }

            /// <summary>
            /// The AccountInfo folder.
            /// </summary>
            [RepositoryFolder("498a0179-b963-46f6-a852-8d522864984e")]
            public virtual ConsumerRegRepoFolders.AccountInfoFolder AccountInfo
            {
                get { return _accountinfo; }
            }

            /// <summary>
            /// The SignMeUp folder.
            /// </summary>
            [RepositoryFolder("1c075f4c-a48d-4e78-adbb-f2e8fadad3a9")]
            public virtual ConsumerRegRepoFolders.SignMeUpFolder SignMeUp
            {
                get { return _signmeup; }
            }
        }

        /// <summary>
        /// The AccountInfoFolder folder.
        /// </summary>
        [RepositoryFolder("498a0179-b963-46f6-a852-8d522864984e")]
        public partial class AccountInfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _firstnameinputInfo;
            RepoItemInfo _lastnameinputInfo;
            RepoItemInfo _emailinputInfo;
            RepoItemInfo _usernameinputInfo;
            RepoItemInfo _passwordinputInfo;
            RepoItemInfo _passwordconfirminputInfo;

            /// <summary>
            /// Creates a new AccountInfo  folder.
            /// </summary>
            public AccountInfoFolder(RepoGenBaseFolder parentFolder) :
                    base("AccountInfo", "/dom/body/div[1]/div[2]/form/fieldset/div[1]/table", parentFolder, 30000, false, "498a0179-b963-46f6-a852-8d522864984e", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "498a0179-b963-46f6-a852-8d522864984e");
                _firstnameinputInfo = new RepoItemInfo(this, "FirstNameInput", "tbody/tr[1]/td[2]/input[@id='txtFirstName']", 30000, null, "567d76c5-e82b-4a7a-987f-15a9cfe51187");
                _lastnameinputInfo = new RepoItemInfo(this, "LastNameInput", "tbody/tr[2]/td[2]/input[@id='txtLastName']", 30000, null, "e3374481-2b70-40bd-b8b2-da078aa565da");
                _emailinputInfo = new RepoItemInfo(this, "EmailInput", "tbody/tr[3]/td[2]/input[@id='txtEmail']", 30000, null, "d34196b3-91bc-4085-88ad-ecb28efddf1a");
                _usernameinputInfo = new RepoItemInfo(this, "UserNameInput", "tbody/tr[4]/td[2]/input[@id='txtUserName']", 30000, null, "04bb78a5-77bb-4900-92c4-2d18886addfd");
                _passwordinputInfo = new RepoItemInfo(this, "PasswordInput", "tbody/tr[5]/td[2]/input[@id='txtPassword']", 30000, null, "8d8a6f64-c81e-43fd-afae-ab74002e3517");
                _passwordconfirminputInfo = new RepoItemInfo(this, "PasswordConfirmInput", "tbody/tr[6]/td[2]/input[@id='txtPasswordConfirm']", 30000, null, "1d3e931a-db8b-4d04-962d-10a0ecdb6f45");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("498a0179-b963-46f6-a852-8d522864984e")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("498a0179-b963-46f6-a852-8d522864984e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstNameInput item.
            /// </summary>
            [RepositoryItem("567d76c5-e82b-4a7a-987f-15a9cfe51187")]
            public virtual Ranorex.InputTag FirstNameInput
            {
                get
                {
                    return _firstnameinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstNameInput item info.
            /// </summary>
            [RepositoryItemInfo("567d76c5-e82b-4a7a-987f-15a9cfe51187")]
            public virtual RepoItemInfo FirstNameInputInfo
            {
                get
                {
                    return _firstnameinputInfo;
                }
            }

            /// <summary>
            /// The LastNameInput item.
            /// </summary>
            [RepositoryItem("e3374481-2b70-40bd-b8b2-da078aa565da")]
            public virtual Ranorex.InputTag LastNameInput
            {
                get
                {
                    return _lastnameinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastNameInput item info.
            /// </summary>
            [RepositoryItemInfo("e3374481-2b70-40bd-b8b2-da078aa565da")]
            public virtual RepoItemInfo LastNameInputInfo
            {
                get
                {
                    return _lastnameinputInfo;
                }
            }

            /// <summary>
            /// The EmailInput item.
            /// </summary>
            [RepositoryItem("d34196b3-91bc-4085-88ad-ecb28efddf1a")]
            public virtual Ranorex.InputTag EmailInput
            {
                get
                {
                    return _emailinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EmailInput item info.
            /// </summary>
            [RepositoryItemInfo("d34196b3-91bc-4085-88ad-ecb28efddf1a")]
            public virtual RepoItemInfo EmailInputInfo
            {
                get
                {
                    return _emailinputInfo;
                }
            }

            /// <summary>
            /// The UserNameInput item.
            /// </summary>
            [RepositoryItem("04bb78a5-77bb-4900-92c4-2d18886addfd")]
            public virtual Ranorex.InputTag UserNameInput
            {
                get
                {
                    return _usernameinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserNameInput item info.
            /// </summary>
            [RepositoryItemInfo("04bb78a5-77bb-4900-92c4-2d18886addfd")]
            public virtual RepoItemInfo UserNameInputInfo
            {
                get
                {
                    return _usernameinputInfo;
                }
            }

            /// <summary>
            /// The PasswordInput item.
            /// </summary>
            [RepositoryItem("8d8a6f64-c81e-43fd-afae-ab74002e3517")]
            public virtual Ranorex.InputTag PasswordInput
            {
                get
                {
                    return _passwordinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PasswordInput item info.
            /// </summary>
            [RepositoryItemInfo("8d8a6f64-c81e-43fd-afae-ab74002e3517")]
            public virtual RepoItemInfo PasswordInputInfo
            {
                get
                {
                    return _passwordinputInfo;
                }
            }

            /// <summary>
            /// The PasswordConfirmInput item.
            /// </summary>
            [RepositoryItem("1d3e931a-db8b-4d04-962d-10a0ecdb6f45")]
            public virtual Ranorex.InputTag PasswordConfirmInput
            {
                get
                {
                    return _passwordconfirminputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PasswordConfirmInput item info.
            /// </summary>
            [RepositoryItemInfo("1d3e931a-db8b-4d04-962d-10a0ecdb6f45")]
            public virtual RepoItemInfo PasswordConfirmInputInfo
            {
                get
                {
                    return _passwordconfirminputInfo;
                }
            }
        }

        /// <summary>
        /// The SignMeUpFolder folder.
        /// </summary>
        [RepositoryFolder("1c075f4c-a48d-4e78-adbb-f2e8fadad3a9")]
        public partial class SignMeUpFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _monthlycheckboxInfo;
            RepoItemInfo _newreleasescheckboxInfo;
            RepoItemInfo _specialcheckboxInfo;

            /// <summary>
            /// Creates a new SignMeUp  folder.
            /// </summary>
            public SignMeUpFolder(RepoGenBaseFolder parentFolder) :
                    base("SignMeUp", "/dom/body/div[1]/div[2]/form/fieldset/div[1]/table/tbody/tr[7]", parentFolder, 30000, false, "1c075f4c-a48d-4e78-adbb-f2e8fadad3a9", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "1c075f4c-a48d-4e78-adbb-f2e8fadad3a9");
                _monthlycheckboxInfo = new RepoItemInfo(this, "MonthlyCheckBox", "td[2]/input[@id='Checkbox1' and @name='cknews876492']", 30000, null, "c66a9efd-3aaa-44f1-aac7-78cbacbf86e4");
                _newreleasescheckboxInfo = new RepoItemInfo(this, "NewReleasesCheckBox", "td[2]/input[@id='Checkbox1' and @name='cknews876494']", 30000, null, "492ab509-0d47-40d3-b023-8a1d5b950230");
                _specialcheckboxInfo = new RepoItemInfo(this, "SpecialCheckBox", "td[2]/input[@id='Checkbox1' and @name='cknews2192942']", 30000, null, "8ef39148-c71e-4dcb-b0f7-8f5d638e5b2e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1c075f4c-a48d-4e78-adbb-f2e8fadad3a9")]
            public virtual Ranorex.TrTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TrTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1c075f4c-a48d-4e78-adbb-f2e8fadad3a9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MonthlyCheckBox item.
            /// </summary>
            [RepositoryItem("c66a9efd-3aaa-44f1-aac7-78cbacbf86e4")]
            public virtual Ranorex.InputTag MonthlyCheckBox
            {
                get
                {
                    return _monthlycheckboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The MonthlyCheckBox item info.
            /// </summary>
            [RepositoryItemInfo("c66a9efd-3aaa-44f1-aac7-78cbacbf86e4")]
            public virtual RepoItemInfo MonthlyCheckBoxInfo
            {
                get
                {
                    return _monthlycheckboxInfo;
                }
            }

            /// <summary>
            /// The NewReleasesCheckBox item.
            /// </summary>
            [RepositoryItem("492ab509-0d47-40d3-b023-8a1d5b950230")]
            public virtual Ranorex.InputTag NewReleasesCheckBox
            {
                get
                {
                    return _newreleasescheckboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NewReleasesCheckBox item info.
            /// </summary>
            [RepositoryItemInfo("492ab509-0d47-40d3-b023-8a1d5b950230")]
            public virtual RepoItemInfo NewReleasesCheckBoxInfo
            {
                get
                {
                    return _newreleasescheckboxInfo;
                }
            }

            /// <summary>
            /// The SpecialCheckBox item.
            /// </summary>
            [RepositoryItem("8ef39148-c71e-4dcb-b0f7-8f5d638e5b2e")]
            public virtual Ranorex.InputTag SpecialCheckBox
            {
                get
                {
                    return _specialcheckboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SpecialCheckBox item info.
            /// </summary>
            [RepositoryItemInfo("8ef39148-c71e-4dcb-b0f7-8f5d638e5b2e")]
            public virtual RepoItemInfo SpecialCheckBoxInfo
            {
                get
                {
                    return _specialcheckboxInfo;
                }
            }
        }

        /// <summary>
        /// The RegStep2PageFolder folder.
        /// </summary>
        [RepositoryFolder("44b91685-e20e-4c7e-848d-fe9a0957bbe9")]
        public partial class RegStep2PageFolder : RepoGenBaseFolder
        {
            ConsumerRegRepoFolders.BillingInfoFolder _billinginfo;
            ConsumerRegRepoFolders.PaymentInfoFolder _paymentinfo;
            RepoItemInfo _ihavereadcheckboxInfo;
            RepoItemInfo _submitbuttonInfo;

            /// <summary>
            /// Creates a new RegStep2Page  folder.
            /// </summary>
            public RegStep2PageFolder(RepoGenBaseFolder parentFolder) :
                    base("RegStep2Page", "", parentFolder, 0, false, "44b91685-e20e-4c7e-848d-fe9a0957bbe9", "")
            {
                _billinginfo = new ConsumerRegRepoFolders.BillingInfoFolder(parentFolder);
                _paymentinfo = new ConsumerRegRepoFolders.PaymentInfoFolder(parentFolder);
                _ihavereadcheckboxInfo = new RepoItemInfo(this, "IHaveReadCheckBox", "/dom/body/div[1]/div[2]/form/div/p/input[@id='cbxTC']", 30000, null, "c19c92cf-01f3-4aab-9ff3-b61de8b5325a");
                _submitbuttonInfo = new RepoItemInfo(this, "SubmitButton", "/dom/body/div[1]/div[2]/form/div/input[@id='btnSubmit']", 30000, null, "b35bbb8a-2a34-48d4-b293-b1fea1890768");
            }

            /// <summary>
            /// The IHaveReadCheckBox item.
            /// </summary>
            [RepositoryItem("c19c92cf-01f3-4aab-9ff3-b61de8b5325a")]
            public virtual Ranorex.InputTag IHaveReadCheckBox
            {
                get
                {
                    return _ihavereadcheckboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The IHaveReadCheckBox item info.
            /// </summary>
            [RepositoryItemInfo("c19c92cf-01f3-4aab-9ff3-b61de8b5325a")]
            public virtual RepoItemInfo IHaveReadCheckBoxInfo
            {
                get
                {
                    return _ihavereadcheckboxInfo;
                }
            }

            /// <summary>
            /// The SubmitButton item.
            /// </summary>
            [RepositoryItem("b35bbb8a-2a34-48d4-b293-b1fea1890768")]
            public virtual Ranorex.InputTag SubmitButton
            {
                get
                {
                    return _submitbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitButton item info.
            /// </summary>
            [RepositoryItemInfo("b35bbb8a-2a34-48d4-b293-b1fea1890768")]
            public virtual RepoItemInfo SubmitButtonInfo
            {
                get
                {
                    return _submitbuttonInfo;
                }
            }

            /// <summary>
            /// The BillingInfo folder.
            /// </summary>
            [RepositoryFolder("2e165d89-7c66-45e0-b6f9-62e0f8c916cd")]
            public virtual ConsumerRegRepoFolders.BillingInfoFolder BillingInfo
            {
                get { return _billinginfo; }
            }

            /// <summary>
            /// The PaymentInfo folder.
            /// </summary>
            [RepositoryFolder("9c752930-ab22-456f-bc3c-f005e369100d")]
            public virtual ConsumerRegRepoFolders.PaymentInfoFolder PaymentInfo
            {
                get { return _paymentinfo; }
            }
        }

        /// <summary>
        /// The BillingInfoFolder folder.
        /// </summary>
        [RepositoryFolder("2e165d89-7c66-45e0-b6f9-62e0f8c916cd")]
        public partial class BillingInfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _companyinputInfo;
            RepoItemInfo _addressinputInfo;
            RepoItemInfo _aptsuiteinputInfo;
            RepoItemInfo _cityinputInfo;
            RepoItemInfo _stateselectInfo;
            RepoItemInfo _phoneinputInfo;
            RepoItemInfo _zipinputInfo;
            RepoItemInfo _countryselectInfo;
            RepoItemInfo _howhearselectInfo;

            /// <summary>
            /// Creates a new BillingInfo  folder.
            /// </summary>
            public BillingInfoFolder(RepoGenBaseFolder parentFolder) :
                    base("BillingInfo", "", parentFolder, 0, false, "2e165d89-7c66-45e0-b6f9-62e0f8c916cd", "")
            {
                _companyinputInfo = new RepoItemInfo(this, "CompanyInput", "/dom/body/div[1]/div[2]/form/fieldset[1]/div[1]/table/tbody/tr[3]/td[2]/input[@id='txtOrgName']", 30000, null, "8542a85a-2a34-4f47-9103-d964f56fc9f0");
                _addressinputInfo = new RepoItemInfo(this, "AddressInput", "/dom/body/div[1]/div[2]/form/fieldset[1]/div[1]/table/tbody/tr[4]/td[@innertext=' *']/input[@id='txtAddress1']", 30000, null, "664f4b3a-5bd8-4120-91bf-c4a367f22fc5");
                _aptsuiteinputInfo = new RepoItemInfo(this, "AptSuiteInput", "/dom/body/div[1]/div[2]/form/fieldset[1]/div[1]/table/tbody/tr[5]/td[2]/input[@id='txtAddress2']", 30000, null, "91e0aa5c-17c3-4836-bb16-900a97ea5f97");
                _cityinputInfo = new RepoItemInfo(this, "CityInput", "/dom/body/div[1]/div[2]/form/fieldset[1]/div[1]/table/tbody/tr[6]/td[@innertext=' *']/input[@id='txtCity']", 30000, null, "b132ada7-c0e9-4f8b-8145-67aa9dad972e");
                _stateselectInfo = new RepoItemInfo(this, "StateSelect", "/dom/body/div[1]/div[2]/form/fieldset[1]/div[1]/table/tbody/tr[7]/td[2]/select[@id='drpState']", 30000, null, "b68d2dea-2271-4448-8c2c-ba96c41806e3");
                _phoneinputInfo = new RepoItemInfo(this, "PhoneInput", "/dom/body/div[1]/div[2]/form/fieldset[1]/div[1]/table/tbody/tr[10]/td[@innertext=' *']/input[@id='txtPhone']", 30000, null, "01619d12-3c5e-4fb2-b970-0caa824da1f4");
                _zipinputInfo = new RepoItemInfo(this, "ZipInput", "/dom/body/div[1]/div[2]/form/fieldset[1]/div[1]/table/tbody/tr[8]/td[2]/input[@id='txtZIP']", 30000, null, "e2fc4ef2-6eba-48b0-ae54-25ac0048f4b7");
                _countryselectInfo = new RepoItemInfo(this, "CountrySelect", "/dom/body/div[1]/div[2]/form/fieldset[1]/div[1]/table/tbody/tr[9]/td[2]/select[@id='drpCountry']", 30000, null, "d95fcca3-32f1-487d-ab7a-d03926636a9f");
                _howhearselectInfo = new RepoItemInfo(this, "HowHearSelect", "/dom/body/div[1]/div[2]/form/fieldset[1]/div[1]/table/tbody/tr[12]/td[2]/select[@id='drpHearAboutUs']", 30000, null, "9699108e-623d-401d-b5cf-7686e89ec905");
            }

            /// <summary>
            /// The CompanyInput item.
            /// </summary>
            [RepositoryItem("8542a85a-2a34-4f47-9103-d964f56fc9f0")]
            public virtual Ranorex.InputTag CompanyInput
            {
                get
                {
                    return _companyinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CompanyInput item info.
            /// </summary>
            [RepositoryItemInfo("8542a85a-2a34-4f47-9103-d964f56fc9f0")]
            public virtual RepoItemInfo CompanyInputInfo
            {
                get
                {
                    return _companyinputInfo;
                }
            }

            /// <summary>
            /// The AddressInput item.
            /// </summary>
            [RepositoryItem("664f4b3a-5bd8-4120-91bf-c4a367f22fc5")]
            public virtual Ranorex.InputTag AddressInput
            {
                get
                {
                    return _addressinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AddressInput item info.
            /// </summary>
            [RepositoryItemInfo("664f4b3a-5bd8-4120-91bf-c4a367f22fc5")]
            public virtual RepoItemInfo AddressInputInfo
            {
                get
                {
                    return _addressinputInfo;
                }
            }

            /// <summary>
            /// The AptSuiteInput item.
            /// </summary>
            [RepositoryItem("91e0aa5c-17c3-4836-bb16-900a97ea5f97")]
            public virtual Ranorex.InputTag AptSuiteInput
            {
                get
                {
                    return _aptsuiteinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AptSuiteInput item info.
            /// </summary>
            [RepositoryItemInfo("91e0aa5c-17c3-4836-bb16-900a97ea5f97")]
            public virtual RepoItemInfo AptSuiteInputInfo
            {
                get
                {
                    return _aptsuiteinputInfo;
                }
            }

            /// <summary>
            /// The CityInput item.
            /// </summary>
            [RepositoryItem("b132ada7-c0e9-4f8b-8145-67aa9dad972e")]
            public virtual Ranorex.InputTag CityInput
            {
                get
                {
                    return _cityinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CityInput item info.
            /// </summary>
            [RepositoryItemInfo("b132ada7-c0e9-4f8b-8145-67aa9dad972e")]
            public virtual RepoItemInfo CityInputInfo
            {
                get
                {
                    return _cityinputInfo;
                }
            }

            /// <summary>
            /// The StateSelect item.
            /// </summary>
            [RepositoryItem("b68d2dea-2271-4448-8c2c-ba96c41806e3")]
            public virtual Ranorex.SelectTag StateSelect
            {
                get
                {
                    return _stateselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The StateSelect item info.
            /// </summary>
            [RepositoryItemInfo("b68d2dea-2271-4448-8c2c-ba96c41806e3")]
            public virtual RepoItemInfo StateSelectInfo
            {
                get
                {
                    return _stateselectInfo;
                }
            }

            /// <summary>
            /// The PhoneInput item.
            /// </summary>
            [RepositoryItem("01619d12-3c5e-4fb2-b970-0caa824da1f4")]
            public virtual Ranorex.InputTag PhoneInput
            {
                get
                {
                    return _phoneinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PhoneInput item info.
            /// </summary>
            [RepositoryItemInfo("01619d12-3c5e-4fb2-b970-0caa824da1f4")]
            public virtual RepoItemInfo PhoneInputInfo
            {
                get
                {
                    return _phoneinputInfo;
                }
            }

            /// <summary>
            /// The ZipInput item.
            /// </summary>
            [RepositoryItem("e2fc4ef2-6eba-48b0-ae54-25ac0048f4b7")]
            public virtual Ranorex.InputTag ZipInput
            {
                get
                {
                    return _zipinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ZipInput item info.
            /// </summary>
            [RepositoryItemInfo("e2fc4ef2-6eba-48b0-ae54-25ac0048f4b7")]
            public virtual RepoItemInfo ZipInputInfo
            {
                get
                {
                    return _zipinputInfo;
                }
            }

            /// <summary>
            /// The CountrySelect item.
            /// </summary>
            [RepositoryItem("d95fcca3-32f1-487d-ab7a-d03926636a9f")]
            public virtual Ranorex.SelectTag CountrySelect
            {
                get
                {
                    return _countryselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CountrySelect item info.
            /// </summary>
            [RepositoryItemInfo("d95fcca3-32f1-487d-ab7a-d03926636a9f")]
            public virtual RepoItemInfo CountrySelectInfo
            {
                get
                {
                    return _countryselectInfo;
                }
            }

            /// <summary>
            /// The HowHearSelect item.
            /// </summary>
            [RepositoryItem("9699108e-623d-401d-b5cf-7686e89ec905")]
            public virtual Ranorex.SelectTag HowHearSelect
            {
                get
                {
                    return _howhearselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The HowHearSelect item info.
            /// </summary>
            [RepositoryItemInfo("9699108e-623d-401d-b5cf-7686e89ec905")]
            public virtual RepoItemInfo HowHearSelectInfo
            {
                get
                {
                    return _howhearselectInfo;
                }
            }
        }

        /// <summary>
        /// The PaymentInfoFolder folder.
        /// </summary>
        [RepositoryFolder("9c752930-ab22-456f-bc3c-f005e369100d")]
        public partial class PaymentInfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _paymenttypeselectInfo;
            RepoItemInfo _cardtypeselectInfo;
            RepoItemInfo _cardnumberinputInfo;
            RepoItemInfo _nameoncardinputInfo;
            RepoItemInfo _cardsecuritycodeinputInfo;
            RepoItemInfo _cardexpirationmonthselectInfo;
            RepoItemInfo _cardexpirationyearselectInfo;

            /// <summary>
            /// Creates a new PaymentInfo  folder.
            /// </summary>
            public PaymentInfoFolder(RepoGenBaseFolder parentFolder) :
                    base("PaymentInfo", "", parentFolder, 0, false, "9c752930-ab22-456f-bc3c-f005e369100d", "")
            {
                _paymenttypeselectInfo = new RepoItemInfo(this, "PaymentTypeSelect", "/dom/body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[1]/td[@innertext~'^\\ \\ \\ \\ \\*\\ \\ \\ \\ \\ \\ ']/select[@id='drpPaymentType']", 30000, null, "9d955540-defb-4cb3-904c-676c318aa03d");
                _cardtypeselectInfo = new RepoItemInfo(this, "CardTypeSelect", "/dom/body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCType']/td[2]/select[@id='drpCreditCardType']", 30000, null, "fe4c0963-613b-4920-92be-b4d3c5e68821");
                _cardnumberinputInfo = new RepoItemInfo(this, "CardNumberInput", "/dom/body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCNumber']/td[2]/input[@id='txtCreditCardNumber']", 30000, null, "aa3db019-fd05-413a-98c9-2181cd2d5117");
                _nameoncardinputInfo = new RepoItemInfo(this, "NameOnCardInput", "/dom/body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCName']/td[2]/input[@id='txtNameOnCard']", 30000, null, "61e11514-bda9-41b6-b041-9b837dfb6d6d");
                _cardsecuritycodeinputInfo = new RepoItemInfo(this, "CardSecurityCodeInput", "/dom/body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCSecurityCode']/td[2]/input[@id='txtCreditCardSecurityCode']", 30000, null, "93614f70-14dc-482d-ba5b-ba146470c748");
                _cardexpirationmonthselectInfo = new RepoItemInfo(this, "CardExpirationMonthSelect", "/dom/body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCExpirationDate']/td[@innertext='/']/select[@id='drpExpirationMonth']", 30000, null, "d9f4fb36-f3e3-43be-892f-d62c9e8846bd");
                _cardexpirationyearselectInfo = new RepoItemInfo(this, "CardExpirationYearSelect", "/dom/body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCExpirationDate']/td[@innertext='/']/select[@id='drpExpirationYear']", 30000, null, "2d846a30-d3e1-4baa-8210-95c46fbe4fd8");
            }

            /// <summary>
            /// The PaymentTypeSelect item.
            /// </summary>
            [RepositoryItem("9d955540-defb-4cb3-904c-676c318aa03d")]
            public virtual Ranorex.SelectTag PaymentTypeSelect
            {
                get
                {
                    return _paymenttypeselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The PaymentTypeSelect item info.
            /// </summary>
            [RepositoryItemInfo("9d955540-defb-4cb3-904c-676c318aa03d")]
            public virtual RepoItemInfo PaymentTypeSelectInfo
            {
                get
                {
                    return _paymenttypeselectInfo;
                }
            }

            /// <summary>
            /// The CardTypeSelect item.
            /// </summary>
            [RepositoryItem("fe4c0963-613b-4920-92be-b4d3c5e68821")]
            public virtual Ranorex.SelectTag CardTypeSelect
            {
                get
                {
                    return _cardtypeselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CardTypeSelect item info.
            /// </summary>
            [RepositoryItemInfo("fe4c0963-613b-4920-92be-b4d3c5e68821")]
            public virtual RepoItemInfo CardTypeSelectInfo
            {
                get
                {
                    return _cardtypeselectInfo;
                }
            }

            /// <summary>
            /// The CardNumberInput item.
            /// </summary>
            [RepositoryItem("aa3db019-fd05-413a-98c9-2181cd2d5117")]
            public virtual Ranorex.InputTag CardNumberInput
            {
                get
                {
                    return _cardnumberinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CardNumberInput item info.
            /// </summary>
            [RepositoryItemInfo("aa3db019-fd05-413a-98c9-2181cd2d5117")]
            public virtual RepoItemInfo CardNumberInputInfo
            {
                get
                {
                    return _cardnumberinputInfo;
                }
            }

            /// <summary>
            /// The NameOnCardInput item.
            /// </summary>
            [RepositoryItem("61e11514-bda9-41b6-b041-9b837dfb6d6d")]
            public virtual Ranorex.InputTag NameOnCardInput
            {
                get
                {
                    return _nameoncardinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NameOnCardInput item info.
            /// </summary>
            [RepositoryItemInfo("61e11514-bda9-41b6-b041-9b837dfb6d6d")]
            public virtual RepoItemInfo NameOnCardInputInfo
            {
                get
                {
                    return _nameoncardinputInfo;
                }
            }

            /// <summary>
            /// The CardSecurityCodeInput item.
            /// </summary>
            [RepositoryItem("93614f70-14dc-482d-ba5b-ba146470c748")]
            public virtual Ranorex.InputTag CardSecurityCodeInput
            {
                get
                {
                    return _cardsecuritycodeinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CardSecurityCodeInput item info.
            /// </summary>
            [RepositoryItemInfo("93614f70-14dc-482d-ba5b-ba146470c748")]
            public virtual RepoItemInfo CardSecurityCodeInputInfo
            {
                get
                {
                    return _cardsecuritycodeinputInfo;
                }
            }

            /// <summary>
            /// The CardExpirationMonthSelect item.
            /// </summary>
            [RepositoryItem("d9f4fb36-f3e3-43be-892f-d62c9e8846bd")]
            public virtual Ranorex.SelectTag CardExpirationMonthSelect
            {
                get
                {
                    return _cardexpirationmonthselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CardExpirationMonthSelect item info.
            /// </summary>
            [RepositoryItemInfo("d9f4fb36-f3e3-43be-892f-d62c9e8846bd")]
            public virtual RepoItemInfo CardExpirationMonthSelectInfo
            {
                get
                {
                    return _cardexpirationmonthselectInfo;
                }
            }

            /// <summary>
            /// The CardExpirationYearSelect item.
            /// </summary>
            [RepositoryItem("2d846a30-d3e1-4baa-8210-95c46fbe4fd8")]
            public virtual Ranorex.SelectTag CardExpirationYearSelect
            {
                get
                {
                    return _cardexpirationyearselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CardExpirationYearSelect item info.
            /// </summary>
            [RepositoryItemInfo("2d846a30-d3e1-4baa-8210-95c46fbe4fd8")]
            public virtual RepoItemInfo CardExpirationYearSelectInfo
            {
                get
                {
                    return _cardexpirationyearselectInfo;
                }
            }
        }

        /// <summary>
        /// The RegConfirmPageFolder folder.
        /// </summary>
        [RepositoryFolder("ec36dfd4-5128-4edd-9022-24b4b099a3b4")]
        public partial class RegConfirmPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logoutlinkInfo;
            RepoItemInfo _printreceiptbuttonInfo;

            /// <summary>
            /// Creates a new RegConfirmPage  folder.
            /// </summary>
            public RegConfirmPageFolder(RepoGenBaseFolder parentFolder) :
                    base("RegConfirmPage", "", parentFolder, 0, false, "ec36dfd4-5128-4edd-9022-24b4b099a3b4", "")
            {
                _logoutlinkInfo = new RepoItemInfo(this, "LogoutLink", "/dom/body/div[@id='eyebrow']/div[1]/ul/li[3]/a/strong[@innertext='log out']", 30000, null, "f4ca70e3-7b3c-4137-b92c-998078fc30c2");
                _printreceiptbuttonInfo = new RepoItemInfo(this, "PrintReceiptButton", "/dom/body/div[4]/div[3]/a/span[@innertext='print receipt']", 30000, null, "8677b82b-9d8c-4eb5-b48f-72c6afe48589");
            }

            /// <summary>
            /// The LogoutLink item.
            /// </summary>
            [RepositoryItem("f4ca70e3-7b3c-4137-b92c-998078fc30c2")]
            public virtual Ranorex.StrongTag LogoutLink
            {
                get
                {
                    return _logoutlinkInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The LogoutLink item info.
            /// </summary>
            [RepositoryItemInfo("f4ca70e3-7b3c-4137-b92c-998078fc30c2")]
            public virtual RepoItemInfo LogoutLinkInfo
            {
                get
                {
                    return _logoutlinkInfo;
                }
            }

            /// <summary>
            /// The PrintReceiptButton item.
            /// </summary>
            [RepositoryItem("8677b82b-9d8c-4eb5-b48f-72c6afe48589")]
            public virtual Ranorex.SpanTag PrintReceiptButton
            {
                get
                {
                    return _printreceiptbuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PrintReceiptButton item info.
            /// </summary>
            [RepositoryItemInfo("8677b82b-9d8c-4eb5-b48f-72c6afe48589")]
            public virtual RepoItemInfo PrintReceiptButtonInfo
            {
                get
                {
                    return _printreceiptbuttonInfo;
                }
            }
        }

    }
}