///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Tests.General.Tests.FreeTrial
{
    /// <summary>
    /// The class representing the FreeTrialrepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    [RepositoryFolder("afaaa5c6-d328-410d-ac03-9af7b6afb9a6")]
    public partial class FreeTrialrepo : RepoGenBaseFolder
    {
        static FreeTrialrepo instance = new FreeTrialrepo();
        FreeTrialrepoFolders.DomAppFolder _dom;
        FreeTrialrepoFolders.ConfirmationpageAppFolder _confirmationpage;

        /// <summary>
        /// Gets the singleton class instance representing the FreeTrialrepo element repository.
        /// </summary>
        [RepositoryFolder("afaaa5c6-d328-410d-ac03-9af7b6afb9a6")]
        public static FreeTrialrepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public FreeTrialrepo() 
            : base("FreeTrialrepo", "", null, 30000, false, "afaaa5c6-d328-410d-ac03-9af7b6afb9a6", "./RepositoryImages\\FreeTrialrepoafaaa5c6.rximgres")
        {
            _dom = new FreeTrialrepoFolders.DomAppFolder(this);
            _confirmationpage = new FreeTrialrepoFolders.ConfirmationpageAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The dom folder.
        /// </summary>
        [RepositoryFolder("0a4c5adb-2c00-4bda-9b87-bd89f71e16c2")]
        public virtual FreeTrialrepoFolders.DomAppFolder dom
        {
            get { return _dom; }
        }

        /// <summary>
        /// The confirmationpage folder.
        /// </summary>
        [RepositoryFolder("dcb0408e-88dc-4ca4-a93c-a5c79e172544")]
        public virtual FreeTrialrepoFolders.ConfirmationpageAppFolder confirmationpage
        {
            get { return _confirmationpage; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    public partial class FreeTrialrepoFolders
    {
        /// <summary>
        /// The DomAppFolder folder.
        /// </summary>
        [RepositoryFolder("0a4c5adb-2c00-4bda-9b87-bd89f71e16c2")]
        public partial class DomAppFolder : RepoGenBaseFolder
        {
            FreeTrialrepoFolders.StarttrialFolder _starttrial;
            FreeTrialrepoFolders.CoursetabsFolder _coursetabs;
            FreeTrialrepoFolders.ActinfoFolder _actinfo;
            FreeTrialrepoFolders.BillinginfoFolder _billinginfo;
            FreeTrialrepoFolders.CctypeFolder _cctype;
            FreeTrialrepoFolders.CcinfoFolder _ccinfo;
            FreeTrialrepoFolders.TermsFolder _terms;
            RepoItemInfo _selfInfo;
            RepoItemInfo _bodyInfo;

            /// <summary>
            /// Creates a new dom  folder.
            /// </summary>
            public DomAppFolder(RepoGenBaseFolder parentFolder) :
                    base("dom", "/dom[@domain='release.lynda.com' and @caption~'^lynda\\.com\\ Online\\ Training']", parentFolder, 30000, false, "0a4c5adb-2c00-4bda-9b87-bd89f71e16c2", "")
            {
                _starttrial = new FreeTrialrepoFolders.StarttrialFolder(this);
                _coursetabs = new FreeTrialrepoFolders.CoursetabsFolder(this);
                _actinfo = new FreeTrialrepoFolders.ActinfoFolder(this);
                _billinginfo = new FreeTrialrepoFolders.BillinginfoFolder(this);
                _cctype = new FreeTrialrepoFolders.CctypeFolder(this);
                _ccinfo = new FreeTrialrepoFolders.CcinfoFolder(this);
                _terms = new FreeTrialrepoFolders.TermsFolder(this);
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "0a4c5adb-2c00-4bda-9b87-bd89f71e16c2");
                _bodyInfo = new RepoItemInfo(this, "body", "body", 30000, null, "1839eaf1-396e-4bae-a8fe-e326a7e7d164");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0a4c5adb-2c00-4bda-9b87-bd89f71e16c2")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0a4c5adb-2c00-4bda-9b87-bd89f71e16c2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The body item.
            /// </summary>
            [RepositoryItem("1839eaf1-396e-4bae-a8fe-e326a7e7d164")]
            public virtual Ranorex.BodyTag body
            {
                get
                {
                    return _bodyInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The body item info.
            /// </summary>
            [RepositoryItemInfo("1839eaf1-396e-4bae-a8fe-e326a7e7d164")]
            public virtual RepoItemInfo bodyInfo
            {
                get
                {
                    return _bodyInfo;
                }
            }

            /// <summary>
            /// The starttrial folder.
            /// </summary>
            [RepositoryFolder("b2c1425d-3354-4934-8ead-6106a3dba5ee")]
            public virtual FreeTrialrepoFolders.StarttrialFolder starttrial
            {
                get { return _starttrial; }
            }

            /// <summary>
            /// The coursetabs folder.
            /// </summary>
            [RepositoryFolder("d34ad04d-155c-4289-bdee-2121af3d9689")]
            public virtual FreeTrialrepoFolders.CoursetabsFolder coursetabs
            {
                get { return _coursetabs; }
            }

            /// <summary>
            /// The actinfo folder.
            /// </summary>
            [RepositoryFolder("5e3fcb51-e0c8-4df0-8ac9-40da7f1a47c8")]
            public virtual FreeTrialrepoFolders.ActinfoFolder actinfo
            {
                get { return _actinfo; }
            }

            /// <summary>
            /// The billinginfo folder.
            /// </summary>
            [RepositoryFolder("dc8a8baa-7ecc-4e7b-94bd-4d70b4f75cb9")]
            public virtual FreeTrialrepoFolders.BillinginfoFolder billinginfo
            {
                get { return _billinginfo; }
            }

            /// <summary>
            /// The cctype folder.
            /// </summary>
            [RepositoryFolder("24a16266-39d2-450a-9b45-add1ef130484")]
            public virtual FreeTrialrepoFolders.CctypeFolder cctype
            {
                get { return _cctype; }
            }

            /// <summary>
            /// The ccinfo folder.
            /// </summary>
            [RepositoryFolder("97d6f5e2-e34f-4aad-908e-db60d0554715")]
            public virtual FreeTrialrepoFolders.CcinfoFolder ccinfo
            {
                get { return _ccinfo; }
            }

            /// <summary>
            /// The terms folder.
            /// </summary>
            [RepositoryFolder("dd0cb3e1-8fd0-47ae-b258-73539ce4363b")]
            public virtual FreeTrialrepoFolders.TermsFolder terms
            {
                get { return _terms; }
            }
        }

        /// <summary>
        /// The StarttrialFolder folder.
        /// </summary>
        [RepositoryFolder("b2c1425d-3354-4934-8ead-6106a3dba5ee")]
        public partial class StarttrialFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _atagstart_free_trialInfo;
            RepoItemInfo _objecttaglynda_video_9653Info;

            /// <summary>
            /// Creates a new starttrial  folder.
            /// </summary>
            public StarttrialFolder(RepoGenBaseFolder parentFolder) :
                    base("starttrial", "body/div[@id='content']", parentFolder, 30000, false, "b2c1425d-3354-4934-8ead-6106a3dba5ee", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "b2c1425d-3354-4934-8ead-6106a3dba5ee");
                _atagstart_free_trialInfo = new RepoItemInfo(this, "ATagStart_free_trial", "div[@id='upper']/a[@innertext='start free trial']", 30000, null, "c6ccdc12-8f53-45a6-a945-0ca8724c09ac");
                _objecttaglynda_video_9653Info = new RepoItemInfo(this, "ObjectTagLynda_video_9653", "div[2]/div/object[@id='lynda-video-9653']", 30000, null, "fdfc1432-9b7f-4228-b505-417fe5c22aac");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b2c1425d-3354-4934-8ead-6106a3dba5ee")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b2c1425d-3354-4934-8ead-6106a3dba5ee")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ATagStart_free_trial item.
            /// </summary>
            [RepositoryItem("c6ccdc12-8f53-45a6-a945-0ca8724c09ac")]
            public virtual Ranorex.ATag ATagStart_free_trial
            {
                get
                {
                    return _atagstart_free_trialInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagStart_free_trial item info.
            /// </summary>
            [RepositoryItemInfo("c6ccdc12-8f53-45a6-a945-0ca8724c09ac")]
            public virtual RepoItemInfo ATagStart_free_trialInfo
            {
                get
                {
                    return _atagstart_free_trialInfo;
                }
            }

            /// <summary>
            /// The ObjectTagLynda_video_9653 item.
            /// </summary>
            [RepositoryItem("fdfc1432-9b7f-4228-b505-417fe5c22aac")]
            public virtual Ranorex.ObjectTag ObjectTagLynda_video_9653
            {
                get
                {
                    return _objecttaglynda_video_9653Info.CreateAdapter<Ranorex.ObjectTag>(true);
                }
            }

            /// <summary>
            /// The ObjectTagLynda_video_9653 item info.
            /// </summary>
            [RepositoryItemInfo("fdfc1432-9b7f-4228-b505-417fe5c22aac")]
            public virtual RepoItemInfo ObjectTagLynda_video_9653Info
            {
                get
                {
                    return _objecttaglynda_video_9653Info;
                }
            }
        }

        /// <summary>
        /// The CoursetabsFolder folder.
        /// </summary>
        [RepositoryFolder("d34ad04d-155c-4289-bdee-2121af3d9689")]
        public partial class CoursetabsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _litagn3dInfo;
            RepoItemInfo _litagaudioInfo;
            RepoItemInfo _litagbusinessInfo;
            RepoItemInfo _litagdesignInfo;
            RepoItemInfo _litagdeveloperInfo;
            RepoItemInfo _litagdocumentariesInfo;
            RepoItemInfo _litagphotographyInfo;
            RepoItemInfo _litagvideoInfo;
            RepoItemInfo _litagwebInfo;

            /// <summary>
            /// Creates a new coursetabs  folder.
            /// </summary>
            public CoursetabsFolder(RepoGenBaseFolder parentFolder) :
                    base("coursetabs", "body/div[@id='content']/div[3]/div", parentFolder, 30000, false, "d34ad04d-155c-4289-bdee-2121af3d9689", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "d34ad04d-155c-4289-bdee-2121af3d9689");
                _litagn3dInfo = new RepoItemInfo(this, "LiTagN3D", "ul/li[@innertext='3D']", 30000, null, "63b1b398-2742-40d3-ba36-f8ac633592e5");
                _litagaudioInfo = new RepoItemInfo(this, "LiTagAudio", "ul/li[@innertext='Audio']", 30000, null, "ef3d39ad-66cb-4147-bb7c-3bedeb21169d");
                _litagbusinessInfo = new RepoItemInfo(this, "LiTagBusiness", "ul/li[@innertext='Business']", 30000, null, "d018236b-fdca-4f53-a282-5e6e46a445ad");
                _litagdesignInfo = new RepoItemInfo(this, "LiTagDesign", "ul/li[@innertext='Design']", 30000, null, "1f56e2c4-fd0c-4e9b-91c2-bd9800fb9cd0");
                _litagdeveloperInfo = new RepoItemInfo(this, "LiTagDeveloper", "ul/li[@innertext='Developer']", 30000, null, "b05621c2-fd42-44c5-b6fe-6878e2173f71");
                _litagdocumentariesInfo = new RepoItemInfo(this, "LiTagDocumentaries", "ul/li[@innertext='Documentaries']", 30000, null, "c9e8ee1a-9987-4fa2-a8c6-9577859d2e5b");
                _litagphotographyInfo = new RepoItemInfo(this, "LiTagPhotography", "ul/li[@innertext='Photography']", 30000, null, "9e98b29d-07a4-4663-a7f7-b2fa88896e47");
                _litagvideoInfo = new RepoItemInfo(this, "LiTagVideo", "ul/li[@innertext='Video']", 30000, null, "dcf6276e-c31d-4554-89c4-9a3c20d9d3cd");
                _litagwebInfo = new RepoItemInfo(this, "LiTagWeb", "ul/li[@innertext='Web']", 30000, null, "6677ffcc-5830-4ab6-899d-05f8e8f35f70");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d34ad04d-155c-4289-bdee-2121af3d9689")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d34ad04d-155c-4289-bdee-2121af3d9689")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LiTagN3D item.
            /// </summary>
            [RepositoryItem("63b1b398-2742-40d3-ba36-f8ac633592e5")]
            public virtual Ranorex.LiTag LiTagN3D
            {
                get
                {
                    return _litagn3dInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagN3D item info.
            /// </summary>
            [RepositoryItemInfo("63b1b398-2742-40d3-ba36-f8ac633592e5")]
            public virtual RepoItemInfo LiTagN3DInfo
            {
                get
                {
                    return _litagn3dInfo;
                }
            }

            /// <summary>
            /// The LiTagAudio item.
            /// </summary>
            [RepositoryItem("ef3d39ad-66cb-4147-bb7c-3bedeb21169d")]
            public virtual Ranorex.LiTag LiTagAudio
            {
                get
                {
                    return _litagaudioInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagAudio item info.
            /// </summary>
            [RepositoryItemInfo("ef3d39ad-66cb-4147-bb7c-3bedeb21169d")]
            public virtual RepoItemInfo LiTagAudioInfo
            {
                get
                {
                    return _litagaudioInfo;
                }
            }

            /// <summary>
            /// The LiTagBusiness item.
            /// </summary>
            [RepositoryItem("d018236b-fdca-4f53-a282-5e6e46a445ad")]
            public virtual Ranorex.LiTag LiTagBusiness
            {
                get
                {
                    return _litagbusinessInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagBusiness item info.
            /// </summary>
            [RepositoryItemInfo("d018236b-fdca-4f53-a282-5e6e46a445ad")]
            public virtual RepoItemInfo LiTagBusinessInfo
            {
                get
                {
                    return _litagbusinessInfo;
                }
            }

            /// <summary>
            /// The LiTagDesign item.
            /// </summary>
            [RepositoryItem("1f56e2c4-fd0c-4e9b-91c2-bd9800fb9cd0")]
            public virtual Ranorex.LiTag LiTagDesign
            {
                get
                {
                    return _litagdesignInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagDesign item info.
            /// </summary>
            [RepositoryItemInfo("1f56e2c4-fd0c-4e9b-91c2-bd9800fb9cd0")]
            public virtual RepoItemInfo LiTagDesignInfo
            {
                get
                {
                    return _litagdesignInfo;
                }
            }

            /// <summary>
            /// The LiTagDeveloper item.
            /// </summary>
            [RepositoryItem("b05621c2-fd42-44c5-b6fe-6878e2173f71")]
            public virtual Ranorex.LiTag LiTagDeveloper
            {
                get
                {
                    return _litagdeveloperInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagDeveloper item info.
            /// </summary>
            [RepositoryItemInfo("b05621c2-fd42-44c5-b6fe-6878e2173f71")]
            public virtual RepoItemInfo LiTagDeveloperInfo
            {
                get
                {
                    return _litagdeveloperInfo;
                }
            }

            /// <summary>
            /// The LiTagDocumentaries item.
            /// </summary>
            [RepositoryItem("c9e8ee1a-9987-4fa2-a8c6-9577859d2e5b")]
            public virtual Ranorex.LiTag LiTagDocumentaries
            {
                get
                {
                    return _litagdocumentariesInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagDocumentaries item info.
            /// </summary>
            [RepositoryItemInfo("c9e8ee1a-9987-4fa2-a8c6-9577859d2e5b")]
            public virtual RepoItemInfo LiTagDocumentariesInfo
            {
                get
                {
                    return _litagdocumentariesInfo;
                }
            }

            /// <summary>
            /// The LiTagPhotography item.
            /// </summary>
            [RepositoryItem("9e98b29d-07a4-4663-a7f7-b2fa88896e47")]
            public virtual Ranorex.LiTag LiTagPhotography
            {
                get
                {
                    return _litagphotographyInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagPhotography item info.
            /// </summary>
            [RepositoryItemInfo("9e98b29d-07a4-4663-a7f7-b2fa88896e47")]
            public virtual RepoItemInfo LiTagPhotographyInfo
            {
                get
                {
                    return _litagphotographyInfo;
                }
            }

            /// <summary>
            /// The LiTagVideo item.
            /// </summary>
            [RepositoryItem("dcf6276e-c31d-4554-89c4-9a3c20d9d3cd")]
            public virtual Ranorex.LiTag LiTagVideo
            {
                get
                {
                    return _litagvideoInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagVideo item info.
            /// </summary>
            [RepositoryItemInfo("dcf6276e-c31d-4554-89c4-9a3c20d9d3cd")]
            public virtual RepoItemInfo LiTagVideoInfo
            {
                get
                {
                    return _litagvideoInfo;
                }
            }

            /// <summary>
            /// The LiTagWeb item.
            /// </summary>
            [RepositoryItem("6677ffcc-5830-4ab6-899d-05f8e8f35f70")]
            public virtual Ranorex.LiTag LiTagWeb
            {
                get
                {
                    return _litagwebInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The LiTagWeb item info.
            /// </summary>
            [RepositoryItemInfo("6677ffcc-5830-4ab6-899d-05f8e8f35f70")]
            public virtual RepoItemInfo LiTagWebInfo
            {
                get
                {
                    return _litagwebInfo;
                }
            }
        }

        /// <summary>
        /// The ActinfoFolder folder.
        /// </summary>
        [RepositoryFolder("5e3fcb51-e0c8-4df0-8ac9-40da7f1a47c8")]
        public partial class ActinfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _passwordconfirmInfo;
            RepoItemInfo _continuebtnInfo;

            /// <summary>
            /// Creates a new actinfo  folder.
            /// </summary>
            public ActinfoFolder(RepoGenBaseFolder parentFolder) :
                    base("actinfo", "body", parentFolder, 30000, false, "5e3fcb51-e0c8-4df0-8ac9-40da7f1a47c8", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "5e3fcb51-e0c8-4df0-8ac9-40da7f1a47c8");
                _firstnameInfo = new RepoItemInfo(this, "firstname", "div[5]/div[2]/form/fieldset/table/tbody/tr[1]/td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']/input[@id='txtFirstName']", 30000, null, "e89388da-a9f4-4cce-8253-edbf16cc17e5");
                _lastnameInfo = new RepoItemInfo(this, "lastname", "div[5]/div[2]/form/fieldset/table/tbody/tr[2]/td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']/input[@id='txtLastName']", 30000, null, "abcb9dd5-21ee-422e-a05c-83c2f47dbba0");
                _emailInfo = new RepoItemInfo(this, "email", "div[5]/div[2]/form/fieldset/table/tbody/tr[3]/td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']/input[@id='txtEmail']", 30000, null, "8e866d1b-14d9-48e9-b257-67c36b612294");
                _usernameInfo = new RepoItemInfo(this, "username", "div[5]/div[2]/form/fieldset/table/tbody/tr[4]/td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']/input[@id='txtUserName']", 30000, null, "209a2e6e-eaab-48e4-ba0b-7fac7dbc68e7");
                _passwordInfo = new RepoItemInfo(this, "password", "div[5]/div[2]/form/fieldset/table/tbody/tr[5]/td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']/input[@id='txtPassword']", 30000, null, "dae8cd21-1bfe-4452-9617-794373d5f146");
                _passwordconfirmInfo = new RepoItemInfo(this, "passwordconfirm", "div[5]/div[2]/form/fieldset/table/tbody/tr[6]/td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']/input[@id='txtPasswordConfirm']", 30000, null, "c4ff070e-5c98-4b66-9bc6-fbadf6960f70");
                _continuebtnInfo = new RepoItemInfo(this, "continuebtn", "div[5]/div[2]/form/span/input[@name='Continue']", 30000, null, "d8889f5c-d8aa-4f4b-b3ba-1e0e16f9dddd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5e3fcb51-e0c8-4df0-8ac9-40da7f1a47c8")]
            public virtual Ranorex.BodyTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5e3fcb51-e0c8-4df0-8ac9-40da7f1a47c8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The firstname item.
            /// </summary>
            [RepositoryItem("e89388da-a9f4-4cce-8253-edbf16cc17e5")]
            public virtual Ranorex.InputTag firstname
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The firstname item info.
            /// </summary>
            [RepositoryItemInfo("e89388da-a9f4-4cce-8253-edbf16cc17e5")]
            public virtual RepoItemInfo firstnameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The lastname item.
            /// </summary>
            [RepositoryItem("abcb9dd5-21ee-422e-a05c-83c2f47dbba0")]
            public virtual Ranorex.InputTag lastname
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The lastname item info.
            /// </summary>
            [RepositoryItemInfo("abcb9dd5-21ee-422e-a05c-83c2f47dbba0")]
            public virtual RepoItemInfo lastnameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The email item.
            /// </summary>
            [RepositoryItem("8e866d1b-14d9-48e9-b257-67c36b612294")]
            public virtual Ranorex.InputTag email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The email item info.
            /// </summary>
            [RepositoryItemInfo("8e866d1b-14d9-48e9-b257-67c36b612294")]
            public virtual RepoItemInfo emailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The username item.
            /// </summary>
            [RepositoryItem("209a2e6e-eaab-48e4-ba0b-7fac7dbc68e7")]
            public virtual Ranorex.InputTag username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The username item info.
            /// </summary>
            [RepositoryItemInfo("209a2e6e-eaab-48e4-ba0b-7fac7dbc68e7")]
            public virtual RepoItemInfo usernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The password item.
            /// </summary>
            [RepositoryItem("dae8cd21-1bfe-4452-9617-794373d5f146")]
            public virtual Ranorex.InputTag password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The password item info.
            /// </summary>
            [RepositoryItemInfo("dae8cd21-1bfe-4452-9617-794373d5f146")]
            public virtual RepoItemInfo passwordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The passwordconfirm item.
            /// </summary>
            [RepositoryItem("c4ff070e-5c98-4b66-9bc6-fbadf6960f70")]
            public virtual Ranorex.InputTag passwordconfirm
            {
                get
                {
                    return _passwordconfirmInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The passwordconfirm item info.
            /// </summary>
            [RepositoryItemInfo("c4ff070e-5c98-4b66-9bc6-fbadf6960f70")]
            public virtual RepoItemInfo passwordconfirmInfo
            {
                get
                {
                    return _passwordconfirmInfo;
                }
            }

            /// <summary>
            /// The continuebtn item.
            /// </summary>
            [RepositoryItem("d8889f5c-d8aa-4f4b-b3ba-1e0e16f9dddd")]
            public virtual Ranorex.InputTag continuebtn
            {
                get
                {
                    return _continuebtnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The continuebtn item info.
            /// </summary>
            [RepositoryItemInfo("d8889f5c-d8aa-4f4b-b3ba-1e0e16f9dddd")]
            public virtual RepoItemInfo continuebtnInfo
            {
                get
                {
                    return _continuebtnInfo;
                }
            }
        }

        /// <summary>
        /// The BillinginfoFolder folder.
        /// </summary>
        [RepositoryFolder("dc8a8baa-7ecc-4e7b-94bd-4d70b4f75cb9")]
        public partial class BillinginfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _countryInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _companyInfo;
            RepoItemInfo _address1Info;
            RepoItemInfo _address2Info;
            RepoItemInfo _cityInfo;
            RepoItemInfo _stateInfo;
            RepoItemInfo _zipInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _phoneInfo;

            /// <summary>
            /// Creates a new billinginfo  folder.
            /// </summary>
            public BillinginfoFolder(RepoGenBaseFolder parentFolder) :
                    base("billinginfo", "body/form/div[2]/div[2]/div[@id='ctl00_main_ucRegistrationStep2_pnl']/div/fieldset[@innertext~'^\\ \\ \\ \\ \\*\\ Required\\ informati']/table", parentFolder, 30000, false, "dc8a8baa-7ecc-4e7b-94bd-4d70b4f75cb9", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "dc8a8baa-7ecc-4e7b-94bd-4d70b4f75cb9");
                _countryInfo = new RepoItemInfo(this, "country", "tbody/tr[1]/td[2]/select[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_drpCountry']", 30000, null, "815b8b0a-3c80-4fb3-8afa-d1dd8868081e");
                _firstnameInfo = new RepoItemInfo(this, "firstname", "tbody/tr[2]/td[2]/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_txtFirstName']", 30000, null, "bbeaf0d1-a2c0-4be3-a38a-7e89c6bea6cb");
                _lastnameInfo = new RepoItemInfo(this, "lastname", "tbody/tr[3]/td[2]/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_txtLastName']", 30000, null, "5a712641-e3ae-49be-81f5-86d0e6314dfd");
                _companyInfo = new RepoItemInfo(this, "company", "tbody/tr[4]/td[2]/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_txtCompany']", 30000, null, "8e752020-87fb-421b-97c9-bc0b74cbe3cc");
                _address1Info = new RepoItemInfo(this, "address1", "tbody/tr[5]/td[2]/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_txtAddress1']", 30000, null, "d7ca824a-2847-49e4-8052-8e87aba4a330");
                _address2Info = new RepoItemInfo(this, "address2", "tbody/tr[6]/td[2]/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_txtAddress2']", 30000, null, "d603bd44-adc3-4742-af00-b02b6b55504c");
                _cityInfo = new RepoItemInfo(this, "city", "tbody/tr[7]/td[2]/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_txtCity']", 30000, null, "04bda1fa-72f1-47cf-93a4-2251c56d988e");
                _stateInfo = new RepoItemInfo(this, "state", "tbody/tr[8]/td[2]/select[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_drpState']", 30000, null, "e2b4950e-9680-418c-8700-146dad640a5f");
                _zipInfo = new RepoItemInfo(this, "zip", "tbody/tr[9]/td[2]/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_txtZIP']", 30000, null, "1fe8e899-a74f-412f-acc3-71f7a27e7059");
                _emailInfo = new RepoItemInfo(this, "email", "tbody/tr[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_rowEmail']/td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_txtBillingEmail']", 30000, null, "0e98e6d5-a852-48f5-a6c8-001315eb73b5");
                _phoneInfo = new RepoItemInfo(this, "phone", "tbody/tr[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_trPhone']/td[2]/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucBillingInfo_txtPhone']", 30000, null, "5f0dd70c-d067-4eeb-96fb-84e228d7e372");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dc8a8baa-7ecc-4e7b-94bd-4d70b4f75cb9")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dc8a8baa-7ecc-4e7b-94bd-4d70b4f75cb9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The country item.
            /// </summary>
            [RepositoryItem("815b8b0a-3c80-4fb3-8afa-d1dd8868081e")]
            public virtual Ranorex.SelectTag country
            {
                get
                {
                    return _countryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The country item info.
            /// </summary>
            [RepositoryItemInfo("815b8b0a-3c80-4fb3-8afa-d1dd8868081e")]
            public virtual RepoItemInfo countryInfo
            {
                get
                {
                    return _countryInfo;
                }
            }

            /// <summary>
            /// The firstname item.
            /// </summary>
            [RepositoryItem("bbeaf0d1-a2c0-4be3-a38a-7e89c6bea6cb")]
            public virtual Ranorex.InputTag firstname
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The firstname item info.
            /// </summary>
            [RepositoryItemInfo("bbeaf0d1-a2c0-4be3-a38a-7e89c6bea6cb")]
            public virtual RepoItemInfo firstnameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The lastname item.
            /// </summary>
            [RepositoryItem("5a712641-e3ae-49be-81f5-86d0e6314dfd")]
            public virtual Ranorex.InputTag lastname
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The lastname item info.
            /// </summary>
            [RepositoryItemInfo("5a712641-e3ae-49be-81f5-86d0e6314dfd")]
            public virtual RepoItemInfo lastnameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The company item.
            /// </summary>
            [RepositoryItem("8e752020-87fb-421b-97c9-bc0b74cbe3cc")]
            public virtual Ranorex.InputTag company
            {
                get
                {
                    return _companyInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The company item info.
            /// </summary>
            [RepositoryItemInfo("8e752020-87fb-421b-97c9-bc0b74cbe3cc")]
            public virtual RepoItemInfo companyInfo
            {
                get
                {
                    return _companyInfo;
                }
            }

            /// <summary>
            /// The address1 item.
            /// </summary>
            [RepositoryItem("d7ca824a-2847-49e4-8052-8e87aba4a330")]
            public virtual Ranorex.InputTag address1
            {
                get
                {
                    return _address1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The address1 item info.
            /// </summary>
            [RepositoryItemInfo("d7ca824a-2847-49e4-8052-8e87aba4a330")]
            public virtual RepoItemInfo address1Info
            {
                get
                {
                    return _address1Info;
                }
            }

            /// <summary>
            /// The address2 item.
            /// </summary>
            [RepositoryItem("d603bd44-adc3-4742-af00-b02b6b55504c")]
            public virtual Ranorex.InputTag address2
            {
                get
                {
                    return _address2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The address2 item info.
            /// </summary>
            [RepositoryItemInfo("d603bd44-adc3-4742-af00-b02b6b55504c")]
            public virtual RepoItemInfo address2Info
            {
                get
                {
                    return _address2Info;
                }
            }

            /// <summary>
            /// The city item.
            /// </summary>
            [RepositoryItem("04bda1fa-72f1-47cf-93a4-2251c56d988e")]
            public virtual Ranorex.InputTag city
            {
                get
                {
                    return _cityInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The city item info.
            /// </summary>
            [RepositoryItemInfo("04bda1fa-72f1-47cf-93a4-2251c56d988e")]
            public virtual RepoItemInfo cityInfo
            {
                get
                {
                    return _cityInfo;
                }
            }

            /// <summary>
            /// The state item.
            /// </summary>
            [RepositoryItem("e2b4950e-9680-418c-8700-146dad640a5f")]
            public virtual Ranorex.SelectTag state
            {
                get
                {
                    return _stateInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The state item info.
            /// </summary>
            [RepositoryItemInfo("e2b4950e-9680-418c-8700-146dad640a5f")]
            public virtual RepoItemInfo stateInfo
            {
                get
                {
                    return _stateInfo;
                }
            }

            /// <summary>
            /// The zip item.
            /// </summary>
            [RepositoryItem("1fe8e899-a74f-412f-acc3-71f7a27e7059")]
            public virtual Ranorex.InputTag zip
            {
                get
                {
                    return _zipInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The zip item info.
            /// </summary>
            [RepositoryItemInfo("1fe8e899-a74f-412f-acc3-71f7a27e7059")]
            public virtual RepoItemInfo zipInfo
            {
                get
                {
                    return _zipInfo;
                }
            }

            /// <summary>
            /// The email item.
            /// </summary>
            [RepositoryItem("0e98e6d5-a852-48f5-a6c8-001315eb73b5")]
            public virtual Ranorex.InputTag email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The email item info.
            /// </summary>
            [RepositoryItemInfo("0e98e6d5-a852-48f5-a6c8-001315eb73b5")]
            public virtual RepoItemInfo emailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The phone item.
            /// </summary>
            [RepositoryItem("5f0dd70c-d067-4eeb-96fb-84e228d7e372")]
            public virtual Ranorex.InputTag phone
            {
                get
                {
                    return _phoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The phone item info.
            /// </summary>
            [RepositoryItemInfo("5f0dd70c-d067-4eeb-96fb-84e228d7e372")]
            public virtual RepoItemInfo phoneInfo
            {
                get
                {
                    return _phoneInfo;
                }
            }
        }

        /// <summary>
        /// The CctypeFolder folder.
        /// </summary>
        [RepositoryFolder("24a16266-39d2-450a-9b45-add1ef130484")]
        public partial class CctypeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _cctypeInfo;

            /// <summary>
            /// Creates a new cctype  folder.
            /// </summary>
            public CctypeFolder(RepoGenBaseFolder parentFolder) :
                    base("cctype", "body/form/div[2]/div[2]/div[@id='ctl00_main_ucRegistrationStep2_pnl']/div", parentFolder, 30000, false, "24a16266-39d2-450a-9b45-add1ef130484", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "24a16266-39d2-450a-9b45-add1ef130484");
                _cctypeInfo = new RepoItemInfo(this, "cctype", "fieldset[4]/div[2]/table/tbody/tr[2]/td[2]/select[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucCreditCard_drpCreditCardType']", 30000, null, "b8b117a2-11d7-4889-b1ba-460be4bbd35d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("24a16266-39d2-450a-9b45-add1ef130484")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("24a16266-39d2-450a-9b45-add1ef130484")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The cctype item.
            /// </summary>
            [RepositoryItem("b8b117a2-11d7-4889-b1ba-460be4bbd35d")]
            public virtual Ranorex.SelectTag cctype
            {
                get
                {
                    return _cctypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The cctype item info.
            /// </summary>
            [RepositoryItemInfo("b8b117a2-11d7-4889-b1ba-460be4bbd35d")]
            public virtual RepoItemInfo cctypeInfo
            {
                get
                {
                    return _cctypeInfo;
                }
            }
        }

        /// <summary>
        /// The CcinfoFolder folder.
        /// </summary>
        [RepositoryFolder("97d6f5e2-e34f-4aad-908e-db60d0554715")]
        public partial class CcinfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _ccnumberInfo;
            RepoItemInfo _ccnameInfo;
            RepoItemInfo _cccodeInfo;
            RepoItemInfo _expmoInfo;
            RepoItemInfo _expyrInfo;

            /// <summary>
            /// Creates a new ccinfo  folder.
            /// </summary>
            public CcinfoFolder(RepoGenBaseFolder parentFolder) :
                    base("ccinfo", "body/form/div[2]/div[2]/div[@id='ctl00_main_ucRegistrationStep2_pnl']/div/fieldset[4]/div[2]/table", parentFolder, 30000, false, "97d6f5e2-e34f-4aad-908e-db60d0554715", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "97d6f5e2-e34f-4aad-908e-db60d0554715");
                _ccnumberInfo = new RepoItemInfo(this, "ccnumber", "tbody/tr[3]/td[2]/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucCreditCard_txtCreditCardNumber']", 30000, null, "145536ef-8a0f-4438-8b09-8bab6692ea55");
                _ccnameInfo = new RepoItemInfo(this, "ccname", "tbody/tr[4]/td[2]/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucCreditCard_txtNameOnCard']", 30000, null, "4ada74b6-653c-4153-b203-34b1d6931f8f");
                _cccodeInfo = new RepoItemInfo(this, "cccode", "tbody/tr[5]/td[2]/input[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucCreditCard_txtCreditCardSecurityCode']", 30000, null, "88fad4e7-ec2f-4571-842f-66c01ee1c057");
                _expmoInfo = new RepoItemInfo(this, "expmo", "tbody/tr[6]/td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ /\\ \\ ']/select[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucCreditCard_drpExpirationMonth']", 30000, null, "bf6563bf-6751-4819-9481-609f2209ab97");
                _expyrInfo = new RepoItemInfo(this, "expyr", "tbody/tr[6]/td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ /\\ \\ ']/select[@id='ctl00_main_ucRegistrationStep2_ucPaymentInformation_ucCreditCard_drpExpirationYear']", 30000, null, "7692a943-5bf5-4e77-8f72-26fc5bd061be");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("97d6f5e2-e34f-4aad-908e-db60d0554715")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("97d6f5e2-e34f-4aad-908e-db60d0554715")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ccnumber item.
            /// </summary>
            [RepositoryItem("145536ef-8a0f-4438-8b09-8bab6692ea55")]
            public virtual Ranorex.InputTag ccnumber
            {
                get
                {
                    return _ccnumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ccnumber item info.
            /// </summary>
            [RepositoryItemInfo("145536ef-8a0f-4438-8b09-8bab6692ea55")]
            public virtual RepoItemInfo ccnumberInfo
            {
                get
                {
                    return _ccnumberInfo;
                }
            }

            /// <summary>
            /// The ccname item.
            /// </summary>
            [RepositoryItem("4ada74b6-653c-4153-b203-34b1d6931f8f")]
            public virtual Ranorex.InputTag ccname
            {
                get
                {
                    return _ccnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ccname item info.
            /// </summary>
            [RepositoryItemInfo("4ada74b6-653c-4153-b203-34b1d6931f8f")]
            public virtual RepoItemInfo ccnameInfo
            {
                get
                {
                    return _ccnameInfo;
                }
            }

            /// <summary>
            /// The cccode item.
            /// </summary>
            [RepositoryItem("88fad4e7-ec2f-4571-842f-66c01ee1c057")]
            public virtual Ranorex.InputTag cccode
            {
                get
                {
                    return _cccodeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The cccode item info.
            /// </summary>
            [RepositoryItemInfo("88fad4e7-ec2f-4571-842f-66c01ee1c057")]
            public virtual RepoItemInfo cccodeInfo
            {
                get
                {
                    return _cccodeInfo;
                }
            }

            /// <summary>
            /// The expmo item.
            /// </summary>
            [RepositoryItem("bf6563bf-6751-4819-9481-609f2209ab97")]
            public virtual Ranorex.SelectTag expmo
            {
                get
                {
                    return _expmoInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The expmo item info.
            /// </summary>
            [RepositoryItemInfo("bf6563bf-6751-4819-9481-609f2209ab97")]
            public virtual RepoItemInfo expmoInfo
            {
                get
                {
                    return _expmoInfo;
                }
            }

            /// <summary>
            /// The expyr item.
            /// </summary>
            [RepositoryItem("7692a943-5bf5-4e77-8f72-26fc5bd061be")]
            public virtual Ranorex.SelectTag expyr
            {
                get
                {
                    return _expyrInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The expyr item info.
            /// </summary>
            [RepositoryItemInfo("7692a943-5bf5-4e77-8f72-26fc5bd061be")]
            public virtual RepoItemInfo expyrInfo
            {
                get
                {
                    return _expyrInfo;
                }
            }
        }

        /// <summary>
        /// The TermsFolder folder.
        /// </summary>
        [RepositoryFolder("dd0cb3e1-8fd0-47ae-b258-73539ce4363b")]
        public partial class TermsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _termsInfo;
            RepoItemInfo _aboutusInfo;
            RepoItemInfo _submitInfo;

            /// <summary>
            /// Creates a new terms  folder.
            /// </summary>
            public TermsFolder(RepoGenBaseFolder parentFolder) :
                    base("terms", "body/form/div[2]/div[2]", parentFolder, 30000, false, "dd0cb3e1-8fd0-47ae-b258-73539ce4363b", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "dd0cb3e1-8fd0-47ae-b258-73539ce4363b");
                _termsInfo = new RepoItemInfo(this, "terms", "div[@innertext='. ']/input[@id='ctl00_main_ucRegistrationStep2_TermsAndConditionsCheckBox1_chkTerms']", 30000, null, "091e3f4e-e505-4e3c-af02-02f9fb525878");
                _aboutusInfo = new RepoItemInfo(this, "aboutus", "div[@id='ctl00_main_ucRegistrationStep2_ucHearAbout_divHearAbout']/select[@id='ctl00_main_ucRegistrationStep2_ucHearAbout_ddlHearAboutUs']", 30000, null, "9b775975-fb48-4cea-8a65-bbf2883f6ea9");
                _submitInfo = new RepoItemInfo(this, "submit", "p/span[1]/input[@id='ctl00_main_ucRegistrationStep2_btnSubmit']", 30000, null, "219864de-707e-49e8-94eb-f94d914f45cb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dd0cb3e1-8fd0-47ae-b258-73539ce4363b")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dd0cb3e1-8fd0-47ae-b258-73539ce4363b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The terms item.
            /// </summary>
            [RepositoryItem("091e3f4e-e505-4e3c-af02-02f9fb525878")]
            public virtual Ranorex.InputTag terms
            {
                get
                {
                    return _termsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The terms item info.
            /// </summary>
            [RepositoryItemInfo("091e3f4e-e505-4e3c-af02-02f9fb525878")]
            public virtual RepoItemInfo termsInfo
            {
                get
                {
                    return _termsInfo;
                }
            }

            /// <summary>
            /// The aboutus item.
            /// </summary>
            [RepositoryItem("9b775975-fb48-4cea-8a65-bbf2883f6ea9")]
            public virtual Ranorex.SelectTag aboutus
            {
                get
                {
                    return _aboutusInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The aboutus item info.
            /// </summary>
            [RepositoryItemInfo("9b775975-fb48-4cea-8a65-bbf2883f6ea9")]
            public virtual RepoItemInfo aboutusInfo
            {
                get
                {
                    return _aboutusInfo;
                }
            }

            /// <summary>
            /// The submit item.
            /// </summary>
            [RepositoryItem("219864de-707e-49e8-94eb-f94d914f45cb")]
            public virtual Ranorex.InputTag submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The submit item info.
            /// </summary>
            [RepositoryItemInfo("219864de-707e-49e8-94eb-f94d914f45cb")]
            public virtual RepoItemInfo submitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }
        }

        /// <summary>
        /// The ConfirmationpageAppFolder folder.
        /// </summary>
        [RepositoryFolder("dcb0408e-88dc-4ca4-a93c-a5c79e172544")]
        public partial class ConfirmationpageAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _confirmationtxtInfo;
            RepoItemInfo _continuebtnInfo;

            /// <summary>
            /// Creates a new confirmationpage  folder.
            /// </summary>
            public ConfirmationpageAppFolder(RepoGenBaseFolder parentFolder) :
                    base("confirmationpage", "/dom[@domain='release.lynda.com']", parentFolder, 30000, false, "dcb0408e-88dc-4ca4-a93c-a5c79e172544", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "dcb0408e-88dc-4ca4-a93c-a5c79e172544");
                _confirmationtxtInfo = new RepoItemInfo(this, "confirmationtxt", "body/form/div[2]/div[2]", 30000, null, "ff4c2117-a03d-4434-9b04-031143344bdb");
                _continuebtnInfo = new RepoItemInfo(this, "continuebtn", "body/form/div[2]/div[2]/p[3]/span/input[@id='ctl00_main_RegistrationConfirmation_btnSubmit']", 30000, null, "70c10694-f999-4d3a-8d12-cab37138a7ff");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dcb0408e-88dc-4ca4-a93c-a5c79e172544")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dcb0408e-88dc-4ca4-a93c-a5c79e172544")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The confirmationtxt item.
            /// </summary>
            [RepositoryItem("ff4c2117-a03d-4434-9b04-031143344bdb")]
            public virtual Ranorex.DivTag confirmationtxt
            {
                get
                {
                    return _confirmationtxtInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The confirmationtxt item info.
            /// </summary>
            [RepositoryItemInfo("ff4c2117-a03d-4434-9b04-031143344bdb")]
            public virtual RepoItemInfo confirmationtxtInfo
            {
                get
                {
                    return _confirmationtxtInfo;
                }
            }

            /// <summary>
            /// The continuebtn item.
            /// </summary>
            [RepositoryItem("70c10694-f999-4d3a-8d12-cab37138a7ff")]
            public virtual Ranorex.InputTag continuebtn
            {
                get
                {
                    return _continuebtnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The continuebtn item info.
            /// </summary>
            [RepositoryItemInfo("70c10694-f999-4d3a-8d12-cab37138a7ff")]
            public virtual RepoItemInfo continuebtnInfo
            {
                get
                {
                    return _continuebtnInfo;
                }
            }
        }

    }
}