///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Tests.General.Tests.GiftSubscription
{
    /// <summary>
    /// The class representing the GiftSubscriptionRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    [RepositoryFolder("7666a42e-f1b5-4226-9873-e2a473aea14e")]
    public partial class GiftSubscriptionRepo : RepoGenBaseFolder
    {
        static GiftSubscriptionRepo instance = new GiftSubscriptionRepo();
        GiftSubscriptionRepoFolders.GiftSubAppFolder _giftsub;
        RepoItemInfo _qtyInfo;

        /// <summary>
        /// Gets the singleton class instance representing the GiftSubscriptionRepo element repository.
        /// </summary>
        [RepositoryFolder("7666a42e-f1b5-4226-9873-e2a473aea14e")]
        public static GiftSubscriptionRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GiftSubscriptionRepo() 
            : base("GiftSubscriptionRepo", "", null, 30000, false, "7666a42e-f1b5-4226-9873-e2a473aea14e", "./RepositoryImages\\GiftSubscriptionRepo7666a42e.rximgres")
        {
            _giftsub = new GiftSubscriptionRepoFolders.GiftSubAppFolder(this);
            _qtyInfo = new RepoItemInfo(this, "qty", "/dom[@domain='release.lynda.com']/body/form/div[3]/div/div/div[2]/div[3]/table/tbody/tr[2]/td[4]/input[@id='ctl00_ContentPlaceHolder1_gvGiftCertificates_ctl02_txtQuantity']", 30000, null, "d4f6f8e7-8790-456b-b5a5-f221e48af8e7");
        }

#region Variables

#endregion

        /// <summary>
        /// The qty item.
        /// </summary>
        [RepositoryItem("d4f6f8e7-8790-456b-b5a5-f221e48af8e7")]
        public virtual Ranorex.InputTag qty
        {
            get
            {
                 return _qtyInfo.CreateAdapter<Ranorex.InputTag>(true);
            }
        }

        /// <summary>
        /// The qty item info.
        /// </summary
        [RepositoryItemInfo("d4f6f8e7-8790-456b-b5a5-f221e48af8e7")]
        public virtual RepoItemInfo qtyInfo
        {
            get
            {
                return _qtyInfo;
            }
        }

        /// <summary>
        /// The GiftSub folder.
        /// </summary>
        [RepositoryFolder("f29f68fc-2b89-460c-b4e7-8ec2c51572c4")]
        public virtual GiftSubscriptionRepoFolders.GiftSubAppFolder GiftSub
        {
            get { return _giftsub; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    public partial class GiftSubscriptionRepoFolders
    {
        /// <summary>
        /// The GiftSubAppFolder folder.
        /// </summary>
        [RepositoryFolder("f29f68fc-2b89-460c-b4e7-8ec2c51572c4")]
        public partial class GiftSubAppFolder : RepoGenBaseFolder
        {
            GiftSubscriptionRepoFolders.GiftSub2Folder _giftsub2;
            GiftSubscriptionRepoFolders.GiftSub3Folder _giftsub3;
            GiftSubscriptionRepoFolders.GiftSub3CreateActFolder _giftsub3createact;
            GiftSubscriptionRepoFolders.BillingInfoFolder _billinginfo;
            GiftSubscriptionRepoFolders.PaymentInfoFolder _paymentinfo;
            GiftSubscriptionRepoFolders.CCInfoFolder _ccinfo;
            RepoItemInfo _selfInfo;
            RepoItemInfo _giftsublinkInfo;
            RepoItemInfo _continuebtnInfo;
            RepoItemInfo _continuebtn2Info;
            RepoItemInfo _submitbtnInfo;
            RepoItemInfo _gotolyndabtnInfo;

            /// <summary>
            /// Creates a new GiftSub  folder.
            /// </summary>
            public GiftSubAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GiftSub", "/dom[@domain='release.lynda.com']", parentFolder, 30000, false, "f29f68fc-2b89-460c-b4e7-8ec2c51572c4", "")
            {
                _giftsub2 = new GiftSubscriptionRepoFolders.GiftSub2Folder(this);
                _giftsub3 = new GiftSubscriptionRepoFolders.GiftSub3Folder(this);
                _giftsub3createact = new GiftSubscriptionRepoFolders.GiftSub3CreateActFolder(this);
                _billinginfo = new GiftSubscriptionRepoFolders.BillingInfoFolder(this);
                _paymentinfo = new GiftSubscriptionRepoFolders.PaymentInfoFolder(this);
                _ccinfo = new GiftSubscriptionRepoFolders.CCInfoFolder(this);
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "f29f68fc-2b89-460c-b4e7-8ec2c51572c4");
                _giftsublinkInfo = new RepoItemInfo(this, "GiftSubLink", "body/div[@id='fat-footer']/div[@id='ajaxedFooter']/div[1]/div[@id='sub_footer']/div[4]/ul/li[7]/a[@innertext='gift subscriptions']", 30000, null, "6a0be08b-d498-464f-8c47-febb7db71d94");
                _continuebtnInfo = new RepoItemInfo(this, "continuebtn", "body/form/div[3]/div/div/div[2]/div[4]/input[@id='ctl00_ContentPlaceHolder1_btnNext']", 30000, null, "7b16ed06-287a-404b-ba98-16e288d01d41");
                _continuebtn2Info = new RepoItemInfo(this, "continuebtn2", "body/form/div[3]/div/div[@id='ctl00_ContentPlaceHolder1_upAppliesTo']/div/div[3]/div[1]/input[@id='ctl00_ContentPlaceHolder1_btnContinue']", 30000, null, "0dbf244e-c471-40be-89b7-6883b431e789");
                _submitbtnInfo = new RepoItemInfo(this, "submitbtn", "body/form/div[3]/div/div[@id='ctl00_ContentPlaceHolder1_Panel1']/div[4]/input[@id='ctl00_ContentPlaceHolder1_btnSubmit']", 30000, null, "67eabb17-35d9-45aa-9004-f6a5d660e537");
                _gotolyndabtnInfo = new RepoItemInfo(this, "gotolyndabtn", "body/form/div[3]/div/div/p[5]/input[@id='ctl00_ContentPlaceHolder1_btnGotoLyndaDotCom']", 30000, null, "eb817e46-33d3-4e5d-8fbe-9aa74d32555d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f29f68fc-2b89-460c-b4e7-8ec2c51572c4")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f29f68fc-2b89-460c-b4e7-8ec2c51572c4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The GiftSubLink item.
            /// </summary>
            [RepositoryItem("6a0be08b-d498-464f-8c47-febb7db71d94")]
            public virtual Ranorex.ATag GiftSubLink
            {
                get
                {
                    return _giftsublinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The GiftSubLink item info.
            /// </summary>
            [RepositoryItemInfo("6a0be08b-d498-464f-8c47-febb7db71d94")]
            public virtual RepoItemInfo GiftSubLinkInfo
            {
                get
                {
                    return _giftsublinkInfo;
                }
            }

            /// <summary>
            /// The continuebtn item.
            /// </summary>
            [RepositoryItem("7b16ed06-287a-404b-ba98-16e288d01d41")]
            public virtual Ranorex.InputTag continuebtn
            {
                get
                {
                    return _continuebtnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The continuebtn item info.
            /// </summary>
            [RepositoryItemInfo("7b16ed06-287a-404b-ba98-16e288d01d41")]
            public virtual RepoItemInfo continuebtnInfo
            {
                get
                {
                    return _continuebtnInfo;
                }
            }

            /// <summary>
            /// The continuebtn2 item.
            /// </summary>
            [RepositoryItem("0dbf244e-c471-40be-89b7-6883b431e789")]
            public virtual Ranorex.InputTag continuebtn2
            {
                get
                {
                    return _continuebtn2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The continuebtn2 item info.
            /// </summary>
            [RepositoryItemInfo("0dbf244e-c471-40be-89b7-6883b431e789")]
            public virtual RepoItemInfo continuebtn2Info
            {
                get
                {
                    return _continuebtn2Info;
                }
            }

            /// <summary>
            /// The submitbtn item.
            /// </summary>
            [RepositoryItem("67eabb17-35d9-45aa-9004-f6a5d660e537")]
            public virtual Ranorex.InputTag submitbtn
            {
                get
                {
                    return _submitbtnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The submitbtn item info.
            /// </summary>
            [RepositoryItemInfo("67eabb17-35d9-45aa-9004-f6a5d660e537")]
            public virtual RepoItemInfo submitbtnInfo
            {
                get
                {
                    return _submitbtnInfo;
                }
            }

            /// <summary>
            /// The gotolyndabtn item.
            /// </summary>
            [RepositoryItem("eb817e46-33d3-4e5d-8fbe-9aa74d32555d")]
            public virtual Ranorex.InputTag gotolyndabtn
            {
                get
                {
                    return _gotolyndabtnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The gotolyndabtn item info.
            /// </summary>
            [RepositoryItemInfo("eb817e46-33d3-4e5d-8fbe-9aa74d32555d")]
            public virtual RepoItemInfo gotolyndabtnInfo
            {
                get
                {
                    return _gotolyndabtnInfo;
                }
            }

            /// <summary>
            /// The GiftSub2 folder.
            /// </summary>
            [RepositoryFolder("5faf6883-3f80-499e-b534-b9277800bd5b")]
            public virtual GiftSubscriptionRepoFolders.GiftSub2Folder GiftSub2
            {
                get { return _giftsub2; }
            }

            /// <summary>
            /// The GiftSub3 folder.
            /// </summary>
            [RepositoryFolder("a9cc4e29-5a78-47da-a3bd-e353580d8864")]
            public virtual GiftSubscriptionRepoFolders.GiftSub3Folder GiftSub3
            {
                get { return _giftsub3; }
            }

            /// <summary>
            /// The GiftSub3CreateAct folder.
            /// </summary>
            [RepositoryFolder("0405964e-fa98-4099-86f2-e3a6fdec5de7")]
            public virtual GiftSubscriptionRepoFolders.GiftSub3CreateActFolder GiftSub3CreateAct
            {
                get { return _giftsub3createact; }
            }

            /// <summary>
            /// The BillingInfo folder.
            /// </summary>
            [RepositoryFolder("3ce9a82f-11e6-4da0-973c-900d13220b83")]
            public virtual GiftSubscriptionRepoFolders.BillingInfoFolder BillingInfo
            {
                get { return _billinginfo; }
            }

            /// <summary>
            /// The PaymentInfo folder.
            /// </summary>
            [RepositoryFolder("855a6b86-8439-4ab9-8097-c93c987921ef")]
            public virtual GiftSubscriptionRepoFolders.PaymentInfoFolder PaymentInfo
            {
                get { return _paymentinfo; }
            }

            /// <summary>
            /// The CCInfo folder.
            /// </summary>
            [RepositoryFolder("aafdcb42-35fa-4f0d-a534-c5bc3339b916")]
            public virtual GiftSubscriptionRepoFolders.CCInfoFolder CCInfo
            {
                get { return _ccinfo; }
            }
        }

        /// <summary>
        /// The GiftSub2Folder folder.
        /// </summary>
        [RepositoryFolder("5faf6883-3f80-499e-b534-b9277800bd5b")]
        public partial class GiftSub2Folder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _email1Info;
            RepoItemInfo _email2Info;
            RepoItemInfo _greetingInfo;
            RepoItemInfo _deliverydateInfo;

            /// <summary>
            /// Creates a new GiftSub2  folder.
            /// </summary>
            public GiftSub2Folder(RepoGenBaseFolder parentFolder) :
                    base("GiftSub2", "body/form/div[3]/div/div[@id='ctl00_ContentPlaceHolder1_upAppliesTo']/div/div[3]/table[@id='ctl00_ContentPlaceHolder1_dtUsers']/tbody/tr/td/table/tbody/tr/td[2]/table", parentFolder, 30000, false, "5faf6883-3f80-499e-b534-b9277800bd5b", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "5faf6883-3f80-499e-b534-b9277800bd5b");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "tbody/tr[1]/td[2]/input[@id='ctl00_ContentPlaceHolder1_dtUsers_ctl00_ucUserGiftSubscribtion_tbFirstName']", 30000, null, "863f6906-9a16-4063-bc81-69092c2ca68e");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "tbody/tr[2]/td[2]/input[@id='ctl00_ContentPlaceHolder1_dtUsers_ctl00_ucUserGiftSubscribtion_tbLastName']", 30000, null, "07108561-aa40-4807-a3ca-b76852695156");
                _email1Info = new RepoItemInfo(this, "Email1", "tbody/tr[3]/td[2]/input[@id='ctl00_ContentPlaceHolder1_dtUsers_ctl00_ucUserGiftSubscribtion_tbRecipientEmail']", 30000, null, "09685080-f0d2-4f87-91cb-c864f50f89db");
                _email2Info = new RepoItemInfo(this, "Email2", "tbody/tr[4]/td[2]/input[@id='ctl00_ContentPlaceHolder1_dtUsers_ctl00_ucUserGiftSubscribtion_tbConfirmEmail']", 30000, null, "01c5a0ae-318c-442a-bd7e-63c1c5c7c798");
                _greetingInfo = new RepoItemInfo(this, "Greeting", "tbody/tr[5]/td[2]/textarea[@id='ctl00_ContentPlaceHolder1_dtUsers_ctl00_ucUserGiftSubscribtion_tbGreetingMessage']", 30000, null, "6a5a3716-5ef1-42fa-9199-c14e135275b8");
                _deliverydateInfo = new RepoItemInfo(this, "DeliveryDate", "tbody/tr[6]/td[2]/input[@id='ctl00_ContentPlaceHolder1_dtUsers_ctl00_ucUserGiftSubscribtion_cpDesiredDeliveryDate']", 30000, null, "5ab9daa2-d0d8-4465-8caa-6777583cba7d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5faf6883-3f80-499e-b534-b9277800bd5b")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5faf6883-3f80-499e-b534-b9277800bd5b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("863f6906-9a16-4063-bc81-69092c2ca68e")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("863f6906-9a16-4063-bc81-69092c2ca68e")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("07108561-aa40-4807-a3ca-b76852695156")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("07108561-aa40-4807-a3ca-b76852695156")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Email1 item.
            /// </summary>
            [RepositoryItem("09685080-f0d2-4f87-91cb-c864f50f89db")]
            public virtual Ranorex.InputTag Email1
            {
                get
                {
                    return _email1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email1 item info.
            /// </summary>
            [RepositoryItemInfo("09685080-f0d2-4f87-91cb-c864f50f89db")]
            public virtual RepoItemInfo Email1Info
            {
                get
                {
                    return _email1Info;
                }
            }

            /// <summary>
            /// The Email2 item.
            /// </summary>
            [RepositoryItem("01c5a0ae-318c-442a-bd7e-63c1c5c7c798")]
            public virtual Ranorex.InputTag Email2
            {
                get
                {
                    return _email2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email2 item info.
            /// </summary>
            [RepositoryItemInfo("01c5a0ae-318c-442a-bd7e-63c1c5c7c798")]
            public virtual RepoItemInfo Email2Info
            {
                get
                {
                    return _email2Info;
                }
            }

            /// <summary>
            /// The Greeting item.
            /// </summary>
            [RepositoryItem("6a5a3716-5ef1-42fa-9199-c14e135275b8")]
            public virtual Ranorex.TextAreaTag Greeting
            {
                get
                {
                    return _greetingInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The Greeting item info.
            /// </summary>
            [RepositoryItemInfo("6a5a3716-5ef1-42fa-9199-c14e135275b8")]
            public virtual RepoItemInfo GreetingInfo
            {
                get
                {
                    return _greetingInfo;
                }
            }

            /// <summary>
            /// The DeliveryDate item.
            /// </summary>
            [RepositoryItem("5ab9daa2-d0d8-4465-8caa-6777583cba7d")]
            public virtual Ranorex.InputTag DeliveryDate
            {
                get
                {
                    return _deliverydateInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The DeliveryDate item info.
            /// </summary>
            [RepositoryItemInfo("5ab9daa2-d0d8-4465-8caa-6777583cba7d")]
            public virtual RepoItemInfo DeliveryDateInfo
            {
                get
                {
                    return _deliverydateInfo;
                }
            }
        }

        /// <summary>
        /// The GiftSub3Folder folder.
        /// </summary>
        [RepositoryFolder("a9cc4e29-5a78-47da-a3bd-e353580d8864")]
        public partial class GiftSub3Folder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _firstname1Info;
            RepoItemInfo _lastname1Info;
            RepoItemInfo _email1Info;
            RepoItemInfo _username1Info;

            /// <summary>
            /// Creates a new GiftSub3  folder.
            /// </summary>
            public GiftSub3Folder(RepoGenBaseFolder parentFolder) :
                    base("GiftSub3", "body/form/div[3]/div/div[4]/div[@id='ctl00_ContentPlaceHolder1_Panel2']/fieldset/table", parentFolder, 30000, false, "a9cc4e29-5a78-47da-a3bd-e353580d8864", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "a9cc4e29-5a78-47da-a3bd-e353580d8864");
                _firstname1Info = new RepoItemInfo(this, "FirstName1", "tbody/tr[1]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucCreateAccount_txtFirstName']", 30000, null, "bd4af285-06b7-448a-890b-9d2c9fd0968b");
                _lastname1Info = new RepoItemInfo(this, "LastName1", "tbody/tr[2]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucCreateAccount_txtLastName']", 30000, null, "6c9ca05d-add5-4706-a3eb-85794a3dbe1a");
                _email1Info = new RepoItemInfo(this, "Email1", "tbody/tr[3]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucCreateAccount_txtEmail']", 30000, null, "e767b4ee-8739-40d1-bc07-61d6f7e1404b");
                _username1Info = new RepoItemInfo(this, "Username1", "tbody/tr[4]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucCreateAccount_txtUsername']", 30000, null, "11f31e7c-8be8-4efb-ab7a-542bca48b033");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a9cc4e29-5a78-47da-a3bd-e353580d8864")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a9cc4e29-5a78-47da-a3bd-e353580d8864")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName1 item.
            /// </summary>
            [RepositoryItem("bd4af285-06b7-448a-890b-9d2c9fd0968b")]
            public virtual Ranorex.InputTag FirstName1
            {
                get
                {
                    return _firstname1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName1 item info.
            /// </summary>
            [RepositoryItemInfo("bd4af285-06b7-448a-890b-9d2c9fd0968b")]
            public virtual RepoItemInfo FirstName1Info
            {
                get
                {
                    return _firstname1Info;
                }
            }

            /// <summary>
            /// The LastName1 item.
            /// </summary>
            [RepositoryItem("6c9ca05d-add5-4706-a3eb-85794a3dbe1a")]
            public virtual Ranorex.InputTag LastName1
            {
                get
                {
                    return _lastname1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName1 item info.
            /// </summary>
            [RepositoryItemInfo("6c9ca05d-add5-4706-a3eb-85794a3dbe1a")]
            public virtual RepoItemInfo LastName1Info
            {
                get
                {
                    return _lastname1Info;
                }
            }

            /// <summary>
            /// The Email1 item.
            /// </summary>
            [RepositoryItem("e767b4ee-8739-40d1-bc07-61d6f7e1404b")]
            public virtual Ranorex.InputTag Email1
            {
                get
                {
                    return _email1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email1 item info.
            /// </summary>
            [RepositoryItemInfo("e767b4ee-8739-40d1-bc07-61d6f7e1404b")]
            public virtual RepoItemInfo Email1Info
            {
                get
                {
                    return _email1Info;
                }
            }

            /// <summary>
            /// The Username1 item.
            /// </summary>
            [RepositoryItem("11f31e7c-8be8-4efb-ab7a-542bca48b033")]
            public virtual Ranorex.InputTag Username1
            {
                get
                {
                    return _username1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username1 item info.
            /// </summary>
            [RepositoryItemInfo("11f31e7c-8be8-4efb-ab7a-542bca48b033")]
            public virtual RepoItemInfo Username1Info
            {
                get
                {
                    return _username1Info;
                }
            }
        }

        /// <summary>
        /// The GiftSub3CreateActFolder folder.
        /// </summary>
        [RepositoryFolder("0405964e-fa98-4099-86f2-e3a6fdec5de7")]
        public partial class GiftSub3CreateActFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _continuebtn3Info;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _password2Info;

            /// <summary>
            /// Creates a new GiftSub3CreateAct  folder.
            /// </summary>
            public GiftSub3CreateActFolder(RepoGenBaseFolder parentFolder) :
                    base("GiftSub3CreateAct", "body/form/div[3]/div/div[4]/div[@id='ctl00_ContentPlaceHolder1_Panel2']", parentFolder, 30000, false, "0405964e-fa98-4099-86f2-e3a6fdec5de7", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "0405964e-fa98-4099-86f2-e3a6fdec5de7");
                _continuebtn3Info = new RepoItemInfo(this, "continuebtn3", "div[1]/input[@id='ctl00_ContentPlaceHolder1_btnContinue']", 30000, null, "c36b8f07-7d88-4a73-93b5-1bb187eac31d");
                _passwordInfo = new RepoItemInfo(this, "Password", "fieldset/table/tbody/tr[5]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucCreateAccount_txtNewPassword']", 30000, null, "d4c82ffe-32a7-443f-8155-f100e1f291c7");
                _password2Info = new RepoItemInfo(this, "Password2", "fieldset/table/tbody/tr[6]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucCreateAccount_txtPasswordConfirm']", 30000, null, "374949c0-0324-4b34-bb5d-0fba3723935f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0405964e-fa98-4099-86f2-e3a6fdec5de7")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0405964e-fa98-4099-86f2-e3a6fdec5de7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The continuebtn3 item.
            /// </summary>
            [RepositoryItem("c36b8f07-7d88-4a73-93b5-1bb187eac31d")]
            public virtual Ranorex.InputTag continuebtn3
            {
                get
                {
                    return _continuebtn3Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The continuebtn3 item info.
            /// </summary>
            [RepositoryItemInfo("c36b8f07-7d88-4a73-93b5-1bb187eac31d")]
            public virtual RepoItemInfo continuebtn3Info
            {
                get
                {
                    return _continuebtn3Info;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("d4c82ffe-32a7-443f-8155-f100e1f291c7")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("d4c82ffe-32a7-443f-8155-f100e1f291c7")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Password2 item.
            /// </summary>
            [RepositoryItem("374949c0-0324-4b34-bb5d-0fba3723935f")]
            public virtual Ranorex.InputTag Password2
            {
                get
                {
                    return _password2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password2 item info.
            /// </summary>
            [RepositoryItemInfo("374949c0-0324-4b34-bb5d-0fba3723935f")]
            public virtual RepoItemInfo Password2Info
            {
                get
                {
                    return _password2Info;
                }
            }
        }

        /// <summary>
        /// The BillingInfoFolder folder.
        /// </summary>
        [RepositoryFolder("3ce9a82f-11e6-4da0-973c-900d13220b83")]
        public partial class BillingInfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _countryInfo;
            RepoItemInfo _firstname2Info;
            RepoItemInfo _lastname2Info;
            RepoItemInfo _orgnameInfo;
            RepoItemInfo _addressInfo;
            RepoItemInfo _aptInfo;
            RepoItemInfo _cityInfo;
            RepoItemInfo _stateInfo;
            RepoItemInfo _zipInfo;

            /// <summary>
            /// Creates a new BillingInfo  folder.
            /// </summary>
            public BillingInfoFolder(RepoGenBaseFolder parentFolder) :
                    base("BillingInfo", "body/form/div[3]/div/div[@id='ctl00_ContentPlaceHolder1_UpdatePanel1']/div/fieldset[@innertext~'^\\ \\ \\ \\ \\*\\ Required\\ informati']/table", parentFolder, 30000, false, "3ce9a82f-11e6-4da0-973c-900d13220b83", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "3ce9a82f-11e6-4da0-973c-900d13220b83");
                _countryInfo = new RepoItemInfo(this, "Country", "tbody/tr[1]/td[2]/select[@id='ctl00_ContentPlaceHolder1_ucBillingInfo_drpCountry']", 30000, null, "ef7344e3-ce46-45e5-9990-1cbce5e6c442");
                _firstname2Info = new RepoItemInfo(this, "FirstName2", "tbody/tr[2]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucBillingInfo_txtFirstName']", 30000, null, "f4fe3acb-fbe1-43a5-b3b2-7a5f796a62a9");
                _lastname2Info = new RepoItemInfo(this, "LastName2", "tbody/tr[3]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucBillingInfo_txtLastName']", 30000, null, "a924e7be-7048-4374-ac19-41ffde98cb61");
                _orgnameInfo = new RepoItemInfo(this, "OrgName", "tbody/tr[4]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucBillingInfo_txtCompany']", 30000, null, "cebf6507-d809-4793-9808-897edc4d68a3");
                _addressInfo = new RepoItemInfo(this, "Address", "tbody/tr[5]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucBillingInfo_txtAddress1']", 30000, null, "e76e6879-de9f-4571-aa80-b2b135fd7e13");
                _aptInfo = new RepoItemInfo(this, "Apt", "tbody/tr[6]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucBillingInfo_txtAddress2']", 30000, null, "afafed55-0ad6-4a1d-b50c-f4488047bbd1");
                _cityInfo = new RepoItemInfo(this, "City", "tbody/tr[7]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucBillingInfo_txtCity']", 30000, null, "16749e8d-72db-402b-8415-47c27ec40c65");
                _stateInfo = new RepoItemInfo(this, "State", "tbody/tr[8]/td[2]/select[@id='ctl00_ContentPlaceHolder1_ucBillingInfo_drpState']", 30000, null, "2a732e46-983c-45a7-aaaf-05aac03d1ec1");
                _zipInfo = new RepoItemInfo(this, "Zip", "tbody/tr[9]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucBillingInfo_txtZIP']", 30000, null, "120b3b0b-2334-4a14-a21f-6df557138de6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3ce9a82f-11e6-4da0-973c-900d13220b83")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3ce9a82f-11e6-4da0-973c-900d13220b83")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Country item.
            /// </summary>
            [RepositoryItem("ef7344e3-ce46-45e5-9990-1cbce5e6c442")]
            public virtual Ranorex.SelectTag Country
            {
                get
                {
                    return _countryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The Country item info.
            /// </summary>
            [RepositoryItemInfo("ef7344e3-ce46-45e5-9990-1cbce5e6c442")]
            public virtual RepoItemInfo CountryInfo
            {
                get
                {
                    return _countryInfo;
                }
            }

            /// <summary>
            /// The FirstName2 item.
            /// </summary>
            [RepositoryItem("f4fe3acb-fbe1-43a5-b3b2-7a5f796a62a9")]
            public virtual Ranorex.InputTag FirstName2
            {
                get
                {
                    return _firstname2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName2 item info.
            /// </summary>
            [RepositoryItemInfo("f4fe3acb-fbe1-43a5-b3b2-7a5f796a62a9")]
            public virtual RepoItemInfo FirstName2Info
            {
                get
                {
                    return _firstname2Info;
                }
            }

            /// <summary>
            /// The LastName2 item.
            /// </summary>
            [RepositoryItem("a924e7be-7048-4374-ac19-41ffde98cb61")]
            public virtual Ranorex.InputTag LastName2
            {
                get
                {
                    return _lastname2Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName2 item info.
            /// </summary>
            [RepositoryItemInfo("a924e7be-7048-4374-ac19-41ffde98cb61")]
            public virtual RepoItemInfo LastName2Info
            {
                get
                {
                    return _lastname2Info;
                }
            }

            /// <summary>
            /// The OrgName item.
            /// </summary>
            [RepositoryItem("cebf6507-d809-4793-9808-897edc4d68a3")]
            public virtual Ranorex.InputTag OrgName
            {
                get
                {
                    return _orgnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The OrgName item info.
            /// </summary>
            [RepositoryItemInfo("cebf6507-d809-4793-9808-897edc4d68a3")]
            public virtual RepoItemInfo OrgNameInfo
            {
                get
                {
                    return _orgnameInfo;
                }
            }

            /// <summary>
            /// The Address item.
            /// </summary>
            [RepositoryItem("e76e6879-de9f-4571-aa80-b2b135fd7e13")]
            public virtual Ranorex.InputTag Address
            {
                get
                {
                    return _addressInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Address item info.
            /// </summary>
            [RepositoryItemInfo("e76e6879-de9f-4571-aa80-b2b135fd7e13")]
            public virtual RepoItemInfo AddressInfo
            {
                get
                {
                    return _addressInfo;
                }
            }

            /// <summary>
            /// The Apt item.
            /// </summary>
            [RepositoryItem("afafed55-0ad6-4a1d-b50c-f4488047bbd1")]
            public virtual Ranorex.InputTag Apt
            {
                get
                {
                    return _aptInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Apt item info.
            /// </summary>
            [RepositoryItemInfo("afafed55-0ad6-4a1d-b50c-f4488047bbd1")]
            public virtual RepoItemInfo AptInfo
            {
                get
                {
                    return _aptInfo;
                }
            }

            /// <summary>
            /// The City item.
            /// </summary>
            [RepositoryItem("16749e8d-72db-402b-8415-47c27ec40c65")]
            public virtual Ranorex.InputTag City
            {
                get
                {
                    return _cityInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The City item info.
            /// </summary>
            [RepositoryItemInfo("16749e8d-72db-402b-8415-47c27ec40c65")]
            public virtual RepoItemInfo CityInfo
            {
                get
                {
                    return _cityInfo;
                }
            }

            /// <summary>
            /// The State item.
            /// </summary>
            [RepositoryItem("2a732e46-983c-45a7-aaaf-05aac03d1ec1")]
            public virtual Ranorex.SelectTag State
            {
                get
                {
                    return _stateInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The State item info.
            /// </summary>
            [RepositoryItemInfo("2a732e46-983c-45a7-aaaf-05aac03d1ec1")]
            public virtual RepoItemInfo StateInfo
            {
                get
                {
                    return _stateInfo;
                }
            }

            /// <summary>
            /// The Zip item.
            /// </summary>
            [RepositoryItem("120b3b0b-2334-4a14-a21f-6df557138de6")]
            public virtual Ranorex.InputTag Zip
            {
                get
                {
                    return _zipInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Zip item info.
            /// </summary>
            [RepositoryItemInfo("120b3b0b-2334-4a14-a21f-6df557138de6")]
            public virtual RepoItemInfo ZipInfo
            {
                get
                {
                    return _zipInfo;
                }
            }
        }

        /// <summary>
        /// The PaymentInfoFolder folder.
        /// </summary>
        [RepositoryFolder("855a6b86-8439-4ab9-8097-c93c987921ef")]
        public partial class PaymentInfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _phoneInfo;
            RepoItemInfo _cardtypeInfo;
            RepoItemInfo _cardnumberInfo;
            RepoItemInfo _continuebtn4Info;
            RepoItemInfo _agreetermsInfo;

            /// <summary>
            /// Creates a new PaymentInfo  folder.
            /// </summary>
            public PaymentInfoFolder(RepoGenBaseFolder parentFolder) :
                    base("PaymentInfo", "body/form/div[3]/div/div[@id='ctl00_ContentPlaceHolder1_UpdatePanel1']/div", parentFolder, 30000, false, "855a6b86-8439-4ab9-8097-c93c987921ef", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "855a6b86-8439-4ab9-8097-c93c987921ef");
                _phoneInfo = new RepoItemInfo(this, "Phone", "fieldset[@innertext~'^\\ \\ \\ \\ \\*\\ Required\\ informati']/table/tbody/tr[@id='ctl00_ContentPlaceHolder1_ucBillingInfo_trPhone']/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucBillingInfo_txtPhone']", 30000, null, "9f61e53e-60c2-4ef9-8110-3aaccf1437ba");
                _cardtypeInfo = new RepoItemInfo(this, "cardType", "fieldset[2]/div[2]/table/tbody/tr[1]/td[2]/select[@id='ctl00_ContentPlaceHolder1_ucCreditCard_drpCreditCardType']", 30000, null, "1e403cb4-09e3-4ac5-8812-df7c741c2f7e");
                _cardnumberInfo = new RepoItemInfo(this, "cardNumber", "fieldset[2]/div[2]/table/tbody/tr[2]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucCreditCard_txtCreditCardNumber']", 30000, null, "7f4c1fb2-46d4-40db-b26f-0b3738ab4ce0");
                _continuebtn4Info = new RepoItemInfo(this, "continuebtn4", "div[4]/input[@id='ctl00_ContentPlaceHolder1_btnContinue']", 30000, null, "db3f9c02-2fb4-4ff5-9fd1-49affe5b4283");
                _agreetermsInfo = new RepoItemInfo(this, "AgreeTerms", "p[@innertext='. ']/input[@id='ctl00_ContentPlaceHolder1_ucTermsAndConditionsCheckBox_chkTerms']", 30000, null, "57a09a3a-5d65-49eb-9395-7493e9a79a8f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("855a6b86-8439-4ab9-8097-c93c987921ef")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("855a6b86-8439-4ab9-8097-c93c987921ef")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Phone item.
            /// </summary>
            [RepositoryItem("9f61e53e-60c2-4ef9-8110-3aaccf1437ba")]
            public virtual Ranorex.InputTag Phone
            {
                get
                {
                    return _phoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Phone item info.
            /// </summary>
            [RepositoryItemInfo("9f61e53e-60c2-4ef9-8110-3aaccf1437ba")]
            public virtual RepoItemInfo PhoneInfo
            {
                get
                {
                    return _phoneInfo;
                }
            }

            /// <summary>
            /// The cardType item.
            /// </summary>
            [RepositoryItem("1e403cb4-09e3-4ac5-8812-df7c741c2f7e")]
            public virtual Ranorex.SelectTag cardType
            {
                get
                {
                    return _cardtypeInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The cardType item info.
            /// </summary>
            [RepositoryItemInfo("1e403cb4-09e3-4ac5-8812-df7c741c2f7e")]
            public virtual RepoItemInfo cardTypeInfo
            {
                get
                {
                    return _cardtypeInfo;
                }
            }

            /// <summary>
            /// The cardNumber item.
            /// </summary>
            [RepositoryItem("7f4c1fb2-46d4-40db-b26f-0b3738ab4ce0")]
            public virtual Ranorex.InputTag cardNumber
            {
                get
                {
                    return _cardnumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The cardNumber item info.
            /// </summary>
            [RepositoryItemInfo("7f4c1fb2-46d4-40db-b26f-0b3738ab4ce0")]
            public virtual RepoItemInfo cardNumberInfo
            {
                get
                {
                    return _cardnumberInfo;
                }
            }

            /// <summary>
            /// The continuebtn4 item.
            /// </summary>
            [RepositoryItem("db3f9c02-2fb4-4ff5-9fd1-49affe5b4283")]
            public virtual Ranorex.InputTag continuebtn4
            {
                get
                {
                    return _continuebtn4Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The continuebtn4 item info.
            /// </summary>
            [RepositoryItemInfo("db3f9c02-2fb4-4ff5-9fd1-49affe5b4283")]
            public virtual RepoItemInfo continuebtn4Info
            {
                get
                {
                    return _continuebtn4Info;
                }
            }

            /// <summary>
            /// The AgreeTerms item.
            /// </summary>
            [RepositoryItem("57a09a3a-5d65-49eb-9395-7493e9a79a8f")]
            public virtual Ranorex.InputTag AgreeTerms
            {
                get
                {
                    return _agreetermsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AgreeTerms item info.
            /// </summary>
            [RepositoryItemInfo("57a09a3a-5d65-49eb-9395-7493e9a79a8f")]
            public virtual RepoItemInfo AgreeTermsInfo
            {
                get
                {
                    return _agreetermsInfo;
                }
            }
        }

        /// <summary>
        /// The CCInfoFolder folder.
        /// </summary>
        [RepositoryFolder("aafdcb42-35fa-4f0d-a534-c5bc3339b916")]
        public partial class CCInfoFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _nameoncardInfo;
            RepoItemInfo _cardsecuritycodeInfo;
            RepoItemInfo _expiremonthInfo;
            RepoItemInfo _expireyearInfo;

            /// <summary>
            /// Creates a new CCInfo  folder.
            /// </summary>
            public CCInfoFolder(RepoGenBaseFolder parentFolder) :
                    base("CCInfo", "body/form/div[3]/div/div[@id='ctl00_ContentPlaceHolder1_UpdatePanel1']/div/fieldset[2]/div[2]/table", parentFolder, 30000, false, "aafdcb42-35fa-4f0d-a534-c5bc3339b916", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "aafdcb42-35fa-4f0d-a534-c5bc3339b916");
                _nameoncardInfo = new RepoItemInfo(this, "nameOnCard", "tbody/tr[3]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucCreditCard_txtNameOnCard']", 30000, null, "b15edfa6-53af-487a-b6a3-7029aeb321a1");
                _cardsecuritycodeInfo = new RepoItemInfo(this, "cardSecurityCode", "tbody/tr[4]/td[2]/input[@id='ctl00_ContentPlaceHolder1_ucCreditCard_txtCreditCardSecurityCode']", 30000, null, "89c6a015-76d3-49b1-9f81-7e2dfe4d09ad");
                _expiremonthInfo = new RepoItemInfo(this, "expireMonth", "tbody/tr[5]/td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ /\\ \\ ']/select[@id='ctl00_ContentPlaceHolder1_ucCreditCard_drpExpirationMonth']", 30000, null, "deb7f729-921d-4bf1-93d1-2731c990feda");
                _expireyearInfo = new RepoItemInfo(this, "expireYear", "tbody/tr[5]/td[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ /\\ \\ ']/select[@id='ctl00_ContentPlaceHolder1_ucCreditCard_drpExpirationYear']", 30000, null, "8985938a-67f1-410a-bf9a-de900edf9ead");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aafdcb42-35fa-4f0d-a534-c5bc3339b916")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aafdcb42-35fa-4f0d-a534-c5bc3339b916")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The nameOnCard item.
            /// </summary>
            [RepositoryItem("b15edfa6-53af-487a-b6a3-7029aeb321a1")]
            public virtual Ranorex.InputTag nameOnCard
            {
                get
                {
                    return _nameoncardInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The nameOnCard item info.
            /// </summary>
            [RepositoryItemInfo("b15edfa6-53af-487a-b6a3-7029aeb321a1")]
            public virtual RepoItemInfo nameOnCardInfo
            {
                get
                {
                    return _nameoncardInfo;
                }
            }

            /// <summary>
            /// The cardSecurityCode item.
            /// </summary>
            [RepositoryItem("89c6a015-76d3-49b1-9f81-7e2dfe4d09ad")]
            public virtual Ranorex.InputTag cardSecurityCode
            {
                get
                {
                    return _cardsecuritycodeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The cardSecurityCode item info.
            /// </summary>
            [RepositoryItemInfo("89c6a015-76d3-49b1-9f81-7e2dfe4d09ad")]
            public virtual RepoItemInfo cardSecurityCodeInfo
            {
                get
                {
                    return _cardsecuritycodeInfo;
                }
            }

            /// <summary>
            /// The expireMonth item.
            /// </summary>
            [RepositoryItem("deb7f729-921d-4bf1-93d1-2731c990feda")]
            public virtual Ranorex.SelectTag expireMonth
            {
                get
                {
                    return _expiremonthInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The expireMonth item info.
            /// </summary>
            [RepositoryItemInfo("deb7f729-921d-4bf1-93d1-2731c990feda")]
            public virtual RepoItemInfo expireMonthInfo
            {
                get
                {
                    return _expiremonthInfo;
                }
            }

            /// <summary>
            /// The expireYear item.
            /// </summary>
            [RepositoryItem("8985938a-67f1-410a-bf9a-de900edf9ead")]
            public virtual Ranorex.SelectTag expireYear
            {
                get
                {
                    return _expireyearInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The expireYear item info.
            /// </summary>
            [RepositoryItemInfo("8985938a-67f1-410a-bf9a-de900edf9ead")]
            public virtual RepoItemInfo expireYearInfo
            {
                get
                {
                    return _expireyearInfo;
                }
            }
        }

    }
}