///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Tests.General.Tests.Story_B_02914_Login
{
    /// <summary>
    /// The class representing the Story_B_02914_LoginRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.2.3"), RepositoryFolder("b0017254-ce36-4185-917b-250caa8ff04b")]
    public partial class Story_B_02914_LoginRepo : RepoGenBaseFolder
    {
        static Story_B_02914_LoginRepo instance = new Story_B_02914_LoginRepo();

        /// <summary>
        /// Gets the singleton class instance representing the Story_B_02914_LoginRepo element repository.
        /// </summary>
        [RepositoryFolder("b0017254-ce36-4185-917b-250caa8ff04b")]
        public static Story_B_02914_LoginRepo Instance
        {
            get { return instance; }
        }

        Story_B_02914_LoginRepoFolders.FormAppFolder _form;
        Story_B_02914_LoginRepoFolders.DOMAppFolder _dom;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Story_B_02914_LoginRepo() 
            : base("Story_B_02914_LoginRepo", "", null, 30000, false)
        {
            _form = new Story_B_02914_LoginRepoFolders.FormAppFolder(this);
            _dom = new Story_B_02914_LoginRepoFolders.DOMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Form folder.
        /// </summary>
        [RepositoryFolder("77812b61-8c32-44da-946d-ebfadb4bcaaf")]
        public virtual Story_B_02914_LoginRepoFolders.FormAppFolder Form
        {
            get { return _form; }
        }

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("f6b5a24e-b67a-4ca9-a9e5-2ebae2201c52")]
        public virtual Story_B_02914_LoginRepoFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class Story_B_02914_LoginRepoFolders
    {
        /// <summary>
        /// The FormAppFolder folder.
        /// </summary>
        [RepositoryFolder("77812b61-8c32-44da-946d-ebfadb4bcaaf")]
        public partial class FormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _navigateeditboxInfo;

            /// <summary>
            /// Creates a new Form  folder.
            /// </summary>
            public FormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form", "/form[@class='IEFrame']", parentFolder, 30000, true, "77812b61-8c32-44da-946d-ebfadb4bcaaf")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "77812b61-8c32-44da-946d-ebfadb4bcaaf");
                _navigateeditboxInfo = new RepoItemInfo(this, "NavigateEditBox", "element[@class='WorkerW']/container/element[@controlid='41477']/text[@class='Edit']", 30000, null, "122d31d8-85c8-4e64-a222-eb8d267ab3fd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("77812b61-8c32-44da-946d-ebfadb4bcaaf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("77812b61-8c32-44da-946d-ebfadb4bcaaf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NavigateEditBox item.
            /// </summary>
            [RepositoryItem("122d31d8-85c8-4e64-a222-eb8d267ab3fd")]
            public virtual Ranorex.Text NavigateEditBox
            {
                get
                {
                    return _navigateeditboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NavigateEditBox item info.
            /// </summary>
            [RepositoryItemInfo("122d31d8-85c8-4e64-a222-eb8d267ab3fd")]
            public virtual RepoItemInfo NavigateEditBoxInfo
            {
                get
                {
                    return _navigateeditboxInfo;
                }
            }
        }

        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("f6b5a24e-b67a-4ca9-a9e5-2ebae2201c52")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            Story_B_02914_LoginRepoFolders.LoginControlAFolder _logincontrola;
            Story_B_02914_LoginRepoFolders.LoginControlBFolder _logincontrolb;
            RepoItemInfo _selfInfo;
            RepoItemInfo _webpageInfo;
            RepoItemInfo _loginlinkInfo;
            RepoItemInfo _logoutlinkInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom[@browsername='IE']", parentFolder, 30000, false, "f6b5a24e-b67a-4ca9-a9e5-2ebae2201c52")
            {
                _logincontrola = new Story_B_02914_LoginRepoFolders.LoginControlAFolder(this);
                _logincontrolb = new Story_B_02914_LoginRepoFolders.LoginControlBFolder(this);
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "f6b5a24e-b67a-4ca9-a9e5-2ebae2201c52");
                _webpageInfo = new RepoItemInfo(this, "WebPage", "", 30000, null, "c791d898-3696-45f6-ab08-f96e8a9e668d");
                _loginlinkInfo = new RepoItemInfo(this, "LoginLink", "body/div[@id='eyebrow']/div[1]/ul/li[4]/a[@id='login-modal']", 5000, null, "c27d7f21-9bdc-4aab-8b52-626ff63d6e0b");
                _logoutlinkInfo = new RepoItemInfo(this, "LogoutLink", "body/div[@id='eyebrow']/div[1]/ul/li/a/strong[@innertext='log out']", 30000, null, "7c238ef7-c1fd-4f2d-97ab-c4ea4a77186e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f6b5a24e-b67a-4ca9-a9e5-2ebae2201c52")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f6b5a24e-b67a-4ca9-a9e5-2ebae2201c52")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WebPage item.
            /// </summary>
            [RepositoryItem("c791d898-3696-45f6-ab08-f96e8a9e668d")]
            public virtual Ranorex.WebDocument WebPage
            {
                get
                {
                    return _webpageInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The WebPage item info.
            /// </summary>
            [RepositoryItemInfo("c791d898-3696-45f6-ab08-f96e8a9e668d")]
            public virtual RepoItemInfo WebPageInfo
            {
                get
                {
                    return _webpageInfo;
                }
            }

            /// <summary>
            /// The LoginLink item.
            /// </summary>
            [RepositoryItem("c27d7f21-9bdc-4aab-8b52-626ff63d6e0b")]
            public virtual Ranorex.ATag LoginLink
            {
                get
                {
                    return _loginlinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LoginLink item info.
            /// </summary>
            [RepositoryItemInfo("c27d7f21-9bdc-4aab-8b52-626ff63d6e0b")]
            public virtual RepoItemInfo LoginLinkInfo
            {
                get
                {
                    return _loginlinkInfo;
                }
            }

            /// <summary>
            /// The LogoutLink item.
            /// </summary>
            [RepositoryItem("7c238ef7-c1fd-4f2d-97ab-c4ea4a77186e")]
            public virtual Ranorex.StrongTag LogoutLink
            {
                get
                {
                    return _logoutlinkInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The LogoutLink item info.
            /// </summary>
            [RepositoryItemInfo("7c238ef7-c1fd-4f2d-97ab-c4ea4a77186e")]
            public virtual RepoItemInfo LogoutLinkInfo
            {
                get
                {
                    return _logoutlinkInfo;
                }
            }

            /// <summary>
            /// The LoginControlA folder.
            /// </summary>
            [RepositoryFolder("10918efe-ad5b-411a-877c-89e66ea48236")]
            public virtual Story_B_02914_LoginRepoFolders.LoginControlAFolder LoginControlA
            {
                get { return _logincontrola; }
            }

            /// <summary>
            /// The LoginControlB folder.
            /// </summary>
            [RepositoryFolder("978e7906-e0ff-4978-9e4b-0cc2b72d6e9b")]
            public virtual Story_B_02914_LoginRepoFolders.LoginControlBFolder LoginControlB
            {
                get { return _logincontrolb; }
            }
        }

        /// <summary>
        /// The LoginControlAFolder folder.
        /// </summary>
        [RepositoryFolder("10918efe-ad5b-411a-877c-89e66ea48236")]
        public partial class LoginControlAFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginbuttonInfo;

            /// <summary>
            /// Creates a new LoginControlA  folder.
            /// </summary>
            public LoginControlAFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginControlA", "body/div[@id='fancybox-wrap']/div/div[@id='fancybox-inner']/iframe/body/div/form/table", parentFolder, 30000, false, "10918efe-ad5b-411a-877c-89e66ea48236")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "10918efe-ad5b-411a-877c-89e66ea48236");
                _usernameInfo = new RepoItemInfo(this, "Username", "tbody/tr[2]/td/input[@id='username']", 30000, null, "091e01b8-b796-447c-b9c3-8613d7835414");
                _passwordInfo = new RepoItemInfo(this, "Password", "tbody/tr[4]/td/input[@id='password']", 30000, null, "082f96f9-9896-4f37-b406-4eae5b69722a");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", "tbody/tr[6]/td/div[@id='login_btn']/a", 30000, null, "aa095a49-b48b-43a3-b9b2-7c05480e756b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("10918efe-ad5b-411a-877c-89e66ea48236")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("10918efe-ad5b-411a-877c-89e66ea48236")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("091e01b8-b796-447c-b9c3-8613d7835414")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("091e01b8-b796-447c-b9c3-8613d7835414")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("082f96f9-9896-4f37-b406-4eae5b69722a")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("082f96f9-9896-4f37-b406-4eae5b69722a")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("aa095a49-b48b-43a3-b9b2-7c05480e756b")]
            public virtual Ranorex.ATag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("aa095a49-b48b-43a3-b9b2-7c05480e756b")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The LoginControlBFolder folder.
        /// </summary>
        [RepositoryFolder("978e7906-e0ff-4978-9e4b-0cc2b72d6e9b")]
        public partial class LoginControlBFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginbuttonInfo;

            /// <summary>
            /// Creates a new LoginControlB  folder.
            /// </summary>
            public LoginControlBFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginControlB", "body/form/div[@id='ctl00_sectionHeader']/div/div[4]/div/div[@id='ctl00_UcHeaderGiftSubscriptions1_UcHeaderLogin1_Panel1']/table", parentFolder, 30000, false, "978e7906-e0ff-4978-9e4b-0cc2b72d6e9b")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "978e7906-e0ff-4978-9e4b-0cc2b72d6e9b");
                _usernameInfo = new RepoItemInfo(this, "Username", "tbody/tr[1]/td[2]/input[@id='ctl00_UcHeaderGiftSubscriptions1_UcHeaderLogin1_txtUsername']", 30000, null, "50a8c184-3b15-46a6-b2be-35f820eed48a");
                _passwordInfo = new RepoItemInfo(this, "Password", "tbody/tr[2]/td[2]/input[@id='ctl00_UcHeaderGiftSubscriptions1_UcHeaderLogin1_txtPassword']", 30000, null, "dd0e1c14-6d1b-4342-a2d6-3fccf24f78db");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", "tbody/tr[3]/td/div/input[@id='ctl00_UcHeaderGiftSubscriptions1_UcHeaderLogin1_btnLogin']", 30000, null, "1e22c792-6502-45b0-b899-8607f17bfd6f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("978e7906-e0ff-4978-9e4b-0cc2b72d6e9b")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("978e7906-e0ff-4978-9e4b-0cc2b72d6e9b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Username item.
            /// </summary>
            [RepositoryItem("50a8c184-3b15-46a6-b2be-35f820eed48a")]
            public virtual Ranorex.InputTag Username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Username item info.
            /// </summary>
            [RepositoryItemInfo("50a8c184-3b15-46a6-b2be-35f820eed48a")]
            public virtual RepoItemInfo UsernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("dd0e1c14-6d1b-4342-a2d6-3fccf24f78db")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("dd0e1c14-6d1b-4342-a2d6-3fccf24f78db")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("1e22c792-6502-45b0-b899-8607f17bfd6f")]
            public virtual Ranorex.InputTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("1e22c792-6502-45b0-b899-8607f17bfd6f")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }
        }

    }
}