///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConsumerPagesAbstract.LyndaHeaderFooterPage1
{
    /// <summary>
    /// The class representing the HeaderRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    [RepositoryFolder("dd5063b8-99c4-4d7c-abae-f8959eebbf1c")]
    public partial class HeaderRepo : RepoGenBaseFolder
    {
        static HeaderRepo instance = new HeaderRepo();
        HeaderRepoFolders.DOMbaseAppFolder _dombase;

        /// <summary>
        /// Gets the singleton class instance representing the HeaderRepo element repository.
        /// </summary>
        [RepositoryFolder("dd5063b8-99c4-4d7c-abae-f8959eebbf1c")]
        public static HeaderRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public HeaderRepo() 
            : base("HeaderRepo", "", null, 30000, false, "dd5063b8-99c4-4d7c-abae-f8959eebbf1c", "./RepositoryImages\\HeaderRepodd5063b8.rximgres")
        {
            _dombase = new HeaderRepoFolders.DOMbaseAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The DOMbase folder.
        /// </summary>
        [RepositoryFolder("b10025bb-d9f1-4980-b9bf-67b402450255")]
        public virtual HeaderRepoFolders.DOMbaseAppFolder DOMbase
        {
            get { return _dombase; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    public partial class HeaderRepoFolders
    {
        /// <summary>
        /// The DOMbaseAppFolder folder.
        /// </summary>
        [RepositoryFolder("b10025bb-d9f1-4980-b9bf-67b402450255")]
        public partial class DOMbaseAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _subscribelinkInfo;
            RepoItemInfo _supportmenuInfo;
            RepoItemInfo _supportmenu_faqsInfo;

            /// <summary>
            /// Creates a new DOMbase  folder.
            /// </summary>
            public DOMbaseAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOMbase", "/dom", parentFolder, 30000, false, "b10025bb-d9f1-4980-b9bf-67b402450255", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "b10025bb-d9f1-4980-b9bf-67b402450255");
                _subscribelinkInfo = new RepoItemInfo(this, "SubscribeLink", "body/div[@id='eyebrow']/div[1]/ul/li[2]/a[@innertext='subscribe']", 30000, null, "b8389e85-ab84-4359-bd14-505deefe5be2");
                _supportmenuInfo = new RepoItemInfo(this, "SupportMenu", "body/div[@id='eyebrow']/div[1]/ul/li[1]/a[@innertext='support']", 30000, null, "2abacfe9-6389-4013-99d5-d9b487f69719");
                _supportmenu_faqsInfo = new RepoItemInfo(this, "SupportMenu_FAQs", "body/div[@id='eyebrow']/div[1]/ul/li[1]/div/ul/li[1]/a[@innertext~'^frequently\\ asked\\ question']", 30000, null, "bff6bc38-ef1c-4745-ad18-b16028a5c68d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b10025bb-d9f1-4980-b9bf-67b402450255")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b10025bb-d9f1-4980-b9bf-67b402450255")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SubscribeLink item.
            /// </summary>
            [RepositoryItem("b8389e85-ab84-4359-bd14-505deefe5be2")]
            public virtual Ranorex.ATag SubscribeLink
            {
                get
                {
                    return _subscribelinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SubscribeLink item info.
            /// </summary>
            [RepositoryItemInfo("b8389e85-ab84-4359-bd14-505deefe5be2")]
            public virtual RepoItemInfo SubscribeLinkInfo
            {
                get
                {
                    return _subscribelinkInfo;
                }
            }

            /// <summary>
            /// The SupportMenu item.
            /// </summary>
            [RepositoryItem("2abacfe9-6389-4013-99d5-d9b487f69719")]
            public virtual Ranorex.ATag SupportMenu
            {
                get
                {
                    return _supportmenuInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SupportMenu item info.
            /// </summary>
            [RepositoryItemInfo("2abacfe9-6389-4013-99d5-d9b487f69719")]
            public virtual RepoItemInfo SupportMenuInfo
            {
                get
                {
                    return _supportmenuInfo;
                }
            }

            /// <summary>
            /// The SupportMenu_FAQs item.
            /// </summary>
            [RepositoryItem("bff6bc38-ef1c-4745-ad18-b16028a5c68d")]
            public virtual Ranorex.ATag SupportMenu_FAQs
            {
                get
                {
                    return _supportmenu_faqsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SupportMenu_FAQs item info.
            /// </summary>
            [RepositoryItemInfo("bff6bc38-ef1c-4745-ad18-b16028a5c68d")]
            public virtual RepoItemInfo SupportMenu_FAQsInfo
            {
                get
                {
                    return _supportmenu_faqsInfo;
                }
            }
        }

    }
}