///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConsumerPagesMain.RegConfirm
{
    /// <summary>
    /// The class representing the OTLPlanInfoRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    [RepositoryFolder("3fcad546-cef4-4d24-8ca7-7a3a4062a81e")]
    public partial class OTLPlanInfoRepo : RepoGenBaseFolder
    {
        static OTLPlanInfoRepo instance = new OTLPlanInfoRepo();
        OTLPlanInfoRepoFolders.DOMAppFolder _dom;

        /// <summary>
        /// Gets the singleton class instance representing the OTLPlanInfoRepo element repository.
        /// </summary>
        [RepositoryFolder("3fcad546-cef4-4d24-8ca7-7a3a4062a81e")]
        public static OTLPlanInfoRepo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public OTLPlanInfoRepo() 
            : base("OTLPlanInfoRepo", "", null, 30000, false, "3fcad546-cef4-4d24-8ca7-7a3a4062a81e", "./RepositoryImages\\OTLPlanInfoRepo3fcad546.rximgres")
        {
            _dom = new OTLPlanInfoRepoFolders.DOMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("2a88a4ef-6070-4d81-974a-6de75b7a1141")]
        public virtual OTLPlanInfoRepoFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    public partial class OTLPlanInfoRepoFolders
    {
        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("2a88a4ef-6070-4d81-974a-6de75b7a1141")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _otlplanpriceInfo;
            RepoItemInfo _otlplannameInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "2a88a4ef-6070-4d81-974a-6de75b7a1141", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "2a88a4ef-6070-4d81-974a-6de75b7a1141");
                _otlplanpriceInfo = new RepoItemInfo(this, "OTLPlanPrice", "body/div[4]/table/tbody/tr[2]/td[@class='price']", 30000, null, "83152af2-e5a5-4ad6-a55a-860c228637be");
                _otlplannameInfo = new RepoItemInfo(this, "OTLPlanName", "body/div[4]/table/tbody/tr[2]/td[@class=null()]", 30000, null, "5ae67476-e64d-4e8f-965d-1714d35df53e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a88a4ef-6070-4d81-974a-6de75b7a1141")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a88a4ef-6070-4d81-974a-6de75b7a1141")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OTLPlanPrice item.
            /// </summary>
            [RepositoryItem("83152af2-e5a5-4ad6-a55a-860c228637be")]
            public virtual Ranorex.TdTag OTLPlanPrice
            {
                get
                {
                    return _otlplanpriceInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The OTLPlanPrice item info.
            /// </summary>
            [RepositoryItemInfo("83152af2-e5a5-4ad6-a55a-860c228637be")]
            public virtual RepoItemInfo OTLPlanPriceInfo
            {
                get
                {
                    return _otlplanpriceInfo;
                }
            }

            /// <summary>
            /// The OTLPlanName item.
            /// </summary>
            [RepositoryItem("5ae67476-e64d-4e8f-965d-1714d35df53e")]
            public virtual Ranorex.TdTag OTLPlanName
            {
                get
                {
                    return _otlplannameInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The OTLPlanName item info.
            /// </summary>
            [RepositoryItemInfo("5ae67476-e64d-4e8f-965d-1714d35df53e")]
            public virtual RepoItemInfo OTLPlanNameInfo
            {
                get
                {
                    return _otlplannameInfo;
                }
            }
        }

    }
}