///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConsumerPagesMain.RegConfirm
{
    /// <summary>
    /// The class representing the RegConfirmRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.2.3"), RepositoryFolder("5baa0d35-4aae-4139-b0a7-6b75cda9eec7")]
    public partial class RegConfirmRepo : RepoGenBaseFolder
    {
        static RegConfirmRepo instance = new RegConfirmRepo();

        /// <summary>
        /// Gets the singleton class instance representing the RegConfirmRepo element repository.
        /// </summary>
        [RepositoryFolder("5baa0d35-4aae-4139-b0a7-6b75cda9eec7")]
        public static RegConfirmRepo Instance
        {
            get { return instance; }
        }

        RegConfirmRepoFolders.DOMAppFolder _dom;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RegConfirmRepo() 
            : base("RegConfirmRepo", "", null, 30000, false)
        {
            _dom = new RegConfirmRepoFolders.DOMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
        public virtual RegConfirmRepoFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class RegConfirmRepoFolders
    {
        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _printreceiptspanInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0");
                _printreceiptspanInfo = new RepoItemInfo(this, "PrintReceiptSpan", "body/div[4]/div[3]/a/span[@innertext='print receipt']", 30000, null, "5ee21bea-e92f-4d23-9c05-066bee7a1d07");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PrintReceiptSpan item.
            /// </summary>
            [RepositoryItem("5ee21bea-e92f-4d23-9c05-066bee7a1d07")]
            public virtual Ranorex.SpanTag PrintReceiptSpan
            {
                get
                {
                    return _printreceiptspanInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PrintReceiptSpan item info.
            /// </summary>
            [RepositoryItemInfo("5ee21bea-e92f-4d23-9c05-066bee7a1d07")]
            public virtual RepoItemInfo PrintReceiptSpanInfo
            {
                get
                {
                    return _printreceiptspanInfo;
                }
            }
        }

    }
}