///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConsumerPagesMain.RegStep2
{
    /// <summary>
    /// The class representing the PaymentInformationRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.2.3"), RepositoryFolder("4c36a5e1-5c67-4d1c-ba57-eb2cbeea98f5")]
    public partial class PaymentInformationRepo : RepoGenBaseFolder
    {
        static PaymentInformationRepo instance = new PaymentInformationRepo();

        /// <summary>
        /// Gets the singleton class instance representing the PaymentInformationRepo element repository.
        /// </summary>
        [RepositoryFolder("4c36a5e1-5c67-4d1c-ba57-eb2cbeea98f5")]
        public static PaymentInformationRepo Instance
        {
            get { return instance; }
        }

        PaymentInformationRepoFolders.DOMAppFolder _dom;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PaymentInformationRepo() 
            : base("PaymentInformationRepo", "", null, 30000, false)
        {
            _dom = new PaymentInformationRepoFolders.DOMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
        public virtual PaymentInformationRepoFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class PaymentInformationRepoFolders
    {
        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _paymenttypeselectInfo;
            RepoItemInfo _amounttdInfo;
            RepoItemInfo _creditcardtypeselectInfo;
            RepoItemInfo _creditcardnumberinputInfo;
            RepoItemInfo _nameoncardinputInfo;
            RepoItemInfo _creditcardsecurityinputInfo;
            RepoItemInfo _expirationmonthselectInfo;
            RepoItemInfo _expirationyearselectInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0");
                _paymenttypeselectInfo = new RepoItemInfo(this, "PaymentTypeSelect", "body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[1]/td/select[@id='drpPaymentType']", 30000, null, "a20e893e-13ef-4ebe-916e-2286f8dd64fb");
                _amounttdInfo = new RepoItemInfo(this, "AmountTD", "body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCAmount']/td[@innertext~'.*subscription\\)$']", 30000, null, "72a54718-eea8-40f7-b040-3354e0e3bd67");
                _creditcardtypeselectInfo = new RepoItemInfo(this, "CreditCardTypeSelect", "body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCType']/td[2]/select[@id='drpCreditCardType']", 30000, null, "bed44469-07c9-4664-8a33-053e5d7a0f36");
                _creditcardnumberinputInfo = new RepoItemInfo(this, "CreditCardNumberInput", "body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCNumber']/td[2]/input[@id='txtCreditCardNumber']", 30000, null, "41de9737-6840-423c-9c13-f630c86003a4");
                _nameoncardinputInfo = new RepoItemInfo(this, "NameOnCardInput", "body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCName']/td[2]/input[@id='txtNameOnCard']", 30000, null, "a5159af1-fecf-49ec-a021-04744652c2c8");
                _creditcardsecurityinputInfo = new RepoItemInfo(this, "CreditCardSecurityInput", "body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCSecurityCode']/td[2]/input[@id='txtCreditCardSecurityCode']", 30000, null, "450f8363-75a7-4528-a895-1984aab32c9b");
                _expirationmonthselectInfo = new RepoItemInfo(this, "ExpirationMonthSelect", "body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCExpirationDate']/td[@innertext='/']/select[@id='drpExpirationMonth']", 30000, null, "a1566cbc-beef-44af-ad4d-f2271d1b6506");
                _expirationyearselectInfo = new RepoItemInfo(this, "ExpirationYearSelect", "body/div[1]/div[2]/form/fieldset[2]/table/tbody/tr[@id='trCCExpirationDate']/td[@innertext='/']/select[@id='drpExpirationYear']", 30000, null, "3a03ccfd-b6d8-4bf1-ae6e-02cfe65f2e9d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PaymentTypeSelect item.
            /// </summary>
            [RepositoryItem("a20e893e-13ef-4ebe-916e-2286f8dd64fb")]
            public virtual Ranorex.SelectTag PaymentTypeSelect
            {
                get
                {
                    return _paymenttypeselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The PaymentTypeSelect item info.
            /// </summary>
            [RepositoryItemInfo("a20e893e-13ef-4ebe-916e-2286f8dd64fb")]
            public virtual RepoItemInfo PaymentTypeSelectInfo
            {
                get
                {
                    return _paymenttypeselectInfo;
                }
            }

            /// <summary>
            /// The AmountTD item.
            /// </summary>
            [RepositoryItem("72a54718-eea8-40f7-b040-3354e0e3bd67")]
            public virtual Ranorex.TdTag AmountTD
            {
                get
                {
                    return _amounttdInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The AmountTD item info.
            /// </summary>
            [RepositoryItemInfo("72a54718-eea8-40f7-b040-3354e0e3bd67")]
            public virtual RepoItemInfo AmountTDInfo
            {
                get
                {
                    return _amounttdInfo;
                }
            }

            /// <summary>
            /// The CreditCardTypeSelect item.
            /// </summary>
            [RepositoryItem("bed44469-07c9-4664-8a33-053e5d7a0f36")]
            public virtual Ranorex.SelectTag CreditCardTypeSelect
            {
                get
                {
                    return _creditcardtypeselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CreditCardTypeSelect item info.
            /// </summary>
            [RepositoryItemInfo("bed44469-07c9-4664-8a33-053e5d7a0f36")]
            public virtual RepoItemInfo CreditCardTypeSelectInfo
            {
                get
                {
                    return _creditcardtypeselectInfo;
                }
            }

            /// <summary>
            /// The CreditCardNumberInput item.
            /// </summary>
            [RepositoryItem("41de9737-6840-423c-9c13-f630c86003a4")]
            public virtual Ranorex.InputTag CreditCardNumberInput
            {
                get
                {
                    return _creditcardnumberinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CreditCardNumberInput item info.
            /// </summary>
            [RepositoryItemInfo("41de9737-6840-423c-9c13-f630c86003a4")]
            public virtual RepoItemInfo CreditCardNumberInputInfo
            {
                get
                {
                    return _creditcardnumberinputInfo;
                }
            }

            /// <summary>
            /// The NameOnCardInput item.
            /// </summary>
            [RepositoryItem("a5159af1-fecf-49ec-a021-04744652c2c8")]
            public virtual Ranorex.InputTag NameOnCardInput
            {
                get
                {
                    return _nameoncardinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The NameOnCardInput item info.
            /// </summary>
            [RepositoryItemInfo("a5159af1-fecf-49ec-a021-04744652c2c8")]
            public virtual RepoItemInfo NameOnCardInputInfo
            {
                get
                {
                    return _nameoncardinputInfo;
                }
            }

            /// <summary>
            /// The CreditCardSecurityInput item.
            /// </summary>
            [RepositoryItem("450f8363-75a7-4528-a895-1984aab32c9b")]
            public virtual Ranorex.InputTag CreditCardSecurityInput
            {
                get
                {
                    return _creditcardsecurityinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CreditCardSecurityInput item info.
            /// </summary>
            [RepositoryItemInfo("450f8363-75a7-4528-a895-1984aab32c9b")]
            public virtual RepoItemInfo CreditCardSecurityInputInfo
            {
                get
                {
                    return _creditcardsecurityinputInfo;
                }
            }

            /// <summary>
            /// The ExpirationMonthSelect item.
            /// </summary>
            [RepositoryItem("a1566cbc-beef-44af-ad4d-f2271d1b6506")]
            public virtual Ranorex.SelectTag ExpirationMonthSelect
            {
                get
                {
                    return _expirationmonthselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ExpirationMonthSelect item info.
            /// </summary>
            [RepositoryItemInfo("a1566cbc-beef-44af-ad4d-f2271d1b6506")]
            public virtual RepoItemInfo ExpirationMonthSelectInfo
            {
                get
                {
                    return _expirationmonthselectInfo;
                }
            }

            /// <summary>
            /// The ExpirationYearSelect item.
            /// </summary>
            [RepositoryItem("3a03ccfd-b6d8-4bf1-ae6e-02cfe65f2e9d")]
            public virtual Ranorex.SelectTag ExpirationYearSelect
            {
                get
                {
                    return _expirationyearselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ExpirationYearSelect item info.
            /// </summary>
            [RepositoryItemInfo("3a03ccfd-b6d8-4bf1-ae6e-02cfe65f2e9d")]
            public virtual RepoItemInfo ExpirationYearSelectInfo
            {
                get
                {
                    return _expirationyearselectInfo;
                }
            }
        }

    }
}