///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConsumerPagesMain.RegStep2
{
    /// <summary>
    /// The class representing the RegPageStep2Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.2.3"), RepositoryFolder("5950c3eb-5975-4e43-b477-23d3bc6cd340")]
    public partial class RegPageStep2Repo : RepoGenBaseFolder
    {
        static RegPageStep2Repo instance = new RegPageStep2Repo();

        /// <summary>
        /// Gets the singleton class instance representing the RegPageStep2Repo element repository.
        /// </summary>
        [RepositoryFolder("5950c3eb-5975-4e43-b477-23d3bc6cd340")]
        public static RegPageStep2Repo Instance
        {
            get { return instance; }
        }

        RegPageStep2RepoFolders.DOMAppFolder _dom;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RegPageStep2Repo() 
            : base("RegPageStep2Repo", "", null, 30000, false)
        {
            _dom = new RegPageStep2RepoFolders.DOMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
        public virtual RegPageStep2RepoFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class RegPageStep2RepoFolders
    {
        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _ihavereadinputInfo;
            RepoItemInfo _startmembershipinputInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0");
                _ihavereadinputInfo = new RepoItemInfo(this, "IHaveReadInput", "body/div[1]/div[2]/form/div/p/input[@id='cbxTC']", 30000, null, "18e7ed2b-285e-482a-91b0-796410119d44");
                _startmembershipinputInfo = new RepoItemInfo(this, "StartMembershipInput", "body/div[1]/div[2]/form/div/input[@id='btnSubmit']", 30000, null, "d5abf932-0ae6-4a67-88d1-efacf52ef14b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8e83c3dd-c9a3-42fe-84b2-0e8afeca1ba0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IHaveReadInput item.
            /// </summary>
            [RepositoryItem("18e7ed2b-285e-482a-91b0-796410119d44")]
            public virtual Ranorex.InputTag IHaveReadInput
            {
                get
                {
                    return _ihavereadinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The IHaveReadInput item info.
            /// </summary>
            [RepositoryItemInfo("18e7ed2b-285e-482a-91b0-796410119d44")]
            public virtual RepoItemInfo IHaveReadInputInfo
            {
                get
                {
                    return _ihavereadinputInfo;
                }
            }

            /// <summary>
            /// The StartMembershipInput item.
            /// </summary>
            [RepositoryItem("d5abf932-0ae6-4a67-88d1-efacf52ef14b")]
            public virtual Ranorex.InputTag StartMembershipInput
            {
                get
                {
                    return _startmembershipinputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The StartMembershipInput item info.
            /// </summary>
            [RepositoryItemInfo("d5abf932-0ae6-4a67-88d1-efacf52ef14b")]
            public virtual RepoItemInfo StartMembershipInputInfo
            {
                get
                {
                    return _startmembershipinputInfo;
                }
            }
        }

    }
}