///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Tests.General.Tests.AdminReports
{
    /// <summary>
    /// The class representing the Adminreportsrepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.2.3"), RepositoryFolder("c6b63f15-2f9e-402f-b660-37bbce5ecb3a")]
    public partial class Adminreportsrepo : RepoGenBaseFolder
    {
        static Adminreportsrepo instance = new Adminreportsrepo();

        /// <summary>
        /// Gets the singleton class instance representing the Adminreportsrepo element repository.
        /// </summary>
        [RepositoryFolder("c6b63f15-2f9e-402f-b660-37bbce5ecb3a")]
        public static Adminreportsrepo Instance
        {
            get { return instance; }
        }

        AdminreportsrepoFolders.WebAppFolder _web;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Adminreportsrepo() 
            : base("Adminreportsrepo", "", null, 30000, false)
        {
            _web = new AdminreportsrepoFolders.WebAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Web folder.
        /// </summary>
        [RepositoryFolder("4ef56098-c866-492f-961b-d60f181e6411")]
        public virtual AdminreportsrepoFolders.WebAppFolder Web
        {
            get { return _web; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class AdminreportsrepoFolders
    {
        /// <summary>
        /// The WebAppFolder folder.
        /// </summary>
        [RepositoryFolder("4ef56098-c866-492f-961b-d60f181e6411")]
        public partial class WebAppFolder : RepoGenBaseFolder
        {
            AdminreportsrepoFolders.WelcomeFolder _welcome;
            RepoItemInfo _selfInfo;

            /// <summary>
            /// Creates a new Web  folder.
            /// </summary>
            public WebAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Web", "/dom[@domain='admin.release.lynda.com']", parentFolder, 30000, false, "4ef56098-c866-492f-961b-d60f181e6411")
            {
                _welcome = new AdminreportsrepoFolders.WelcomeFolder(this);
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "4ef56098-c866-492f-961b-d60f181e6411");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4ef56098-c866-492f-961b-d60f181e6411")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4ef56098-c866-492f-961b-d60f181e6411")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Welcome folder.
            /// </summary>
            [RepositoryFolder("5eb0844d-689a-424f-88d7-2e077664486a")]
            public virtual AdminreportsrepoFolders.WelcomeFolder Welcome
            {
                get { return _welcome; }
            }
        }

        /// <summary>
        /// The WelcomeFolder folder.
        /// </summary>
        [RepositoryFolder("5eb0844d-689a-424f-88d7-2e077664486a")]
        public partial class WelcomeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _loginbtnInfo;
            RepoItemInfo _passwordInfo;

            /// <summary>
            /// Creates a new Welcome  folder.
            /// </summary>
            public WelcomeFolder(RepoGenBaseFolder parentFolder) :
                    base("Welcome", "body/form/div[3]/table/tbody/tr/td[9]/div/table", parentFolder, 30000, false, "5eb0844d-689a-424f-88d7-2e077664486a")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "5eb0844d-689a-424f-88d7-2e077664486a");
                _usernameInfo = new RepoItemInfo(this, "username", "tbody/tr[1]/td[2]/input[@id='ctl00_UcHeaderAdminLogin1_txtUsername']", 30000, null, "698ab586-0410-4be6-8c1b-b2a34d4deb2d");
                _loginbtnInfo = new RepoItemInfo(this, "loginbtn", "tbody/tr[1]/td[3]/input[@id='ctl00_UcHeaderAdminLogin1_ImageButton1']", 30000, null, "c7bf49db-2d90-4818-a485-d24bcf1c72f4");
                _passwordInfo = new RepoItemInfo(this, "password", "tbody/tr[2]/td[2]/input[@id='ctl00_UcHeaderAdminLogin1_txtPassword']", 30000, null, "f6dd491b-43e6-470e-84d8-ba9fe96a3c54");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5eb0844d-689a-424f-88d7-2e077664486a")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5eb0844d-689a-424f-88d7-2e077664486a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The username item.
            /// </summary>
            [RepositoryItem("698ab586-0410-4be6-8c1b-b2a34d4deb2d")]
            public virtual Ranorex.InputTag username
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The username item info.
            /// </summary>
            [RepositoryItemInfo("698ab586-0410-4be6-8c1b-b2a34d4deb2d")]
            public virtual RepoItemInfo usernameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The loginbtn item.
            /// </summary>
            [RepositoryItem("c7bf49db-2d90-4818-a485-d24bcf1c72f4")]
            public virtual Ranorex.InputTag loginbtn
            {
                get
                {
                    return _loginbtnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The loginbtn item info.
            /// </summary>
            [RepositoryItemInfo("c7bf49db-2d90-4818-a485-d24bcf1c72f4")]
            public virtual RepoItemInfo loginbtnInfo
            {
                get
                {
                    return _loginbtnInfo;
                }
            }

            /// <summary>
            /// The password item.
            /// </summary>
            [RepositoryItem("f6dd491b-43e6-470e-84d8-ba9fe96a3c54")]
            public virtual Ranorex.InputTag password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The password item info.
            /// </summary>
            [RepositoryItemInfo("f6dd491b-43e6-470e-84d8-ba9fe96a3c54")]
            public virtual RepoItemInfo passwordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }
        }

    }
}