///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Tests.General.Tests.ActivationKey
{
    /// <summary>
    /// The class representing the repoActivationKey element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.2.3"), RepositoryFolder("95298a2b-bae5-4ecb-a7cc-a2577c874313")]
    public partial class repoActivationKey : RepoGenBaseFolder
    {
        static repoActivationKey instance = new repoActivationKey();

        /// <summary>
        /// Gets the singleton class instance representing the repoActivationKey element repository.
        /// </summary>
        [RepositoryFolder("95298a2b-bae5-4ecb-a7cc-a2577c874313")]
        public static repoActivationKey Instance
        {
            get { return instance; }
        }

        repoActivationKeyFolders.WebDocumentSoftware_training_onlineAppFolder _webdocumentsoftware_training_online;
        repoActivationKeyFolders.WebDocumentLynda_com_Online_TraininAppFolder _webdocumentlynda_com_online_trainin;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public repoActivationKey() 
            : base("repoActivationKey", "", null, 30000, false)
        {
            _webdocumentsoftware_training_online = new repoActivationKeyFolders.WebDocumentSoftware_training_onlineAppFolder(this);
            _webdocumentlynda_com_online_trainin = new repoActivationKeyFolders.WebDocumentLynda_com_Online_TraininAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The WebDocumentSoftware_training_online folder.
        /// </summary>
        [RepositoryFolder("2f8413b4-f347-43d1-9051-da2b02e6b5a8")]
        public virtual repoActivationKeyFolders.WebDocumentSoftware_training_onlineAppFolder WebDocumentSoftware_training_online
        {
            get { return _webdocumentsoftware_training_online; }
        }

        /// <summary>
        /// The WebDocumentLynda_com_Online_Trainin folder.
        /// </summary>
        [RepositoryFolder("d9e81a5f-7c78-49b4-8bc7-7a27035de5d3")]
        public virtual repoActivationKeyFolders.WebDocumentLynda_com_Online_TraininAppFolder WebDocumentLynda_com_Online_Trainin
        {
            get { return _webdocumentlynda_com_online_trainin; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class repoActivationKeyFolders
    {
        /// <summary>
        /// The WebDocumentSoftware_training_onlineAppFolder folder.
        /// </summary>
        [RepositoryFolder("2f8413b4-f347-43d1-9051-da2b02e6b5a8")]
        public partial class WebDocumentSoftware_training_onlineAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _atagregister_activation_keyInfo;

            /// <summary>
            /// Creates a new WebDocumentSoftware_training_online  folder.
            /// </summary>
            public WebDocumentSoftware_training_onlineAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WebDocumentSoftware_training_online", "/dom[1]", parentFolder, 30000, false, "2f8413b4-f347-43d1-9051-da2b02e6b5a8")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "2f8413b4-f347-43d1-9051-da2b02e6b5a8");
                _atagregister_activation_keyInfo = new RepoItemInfo(this, "ATagRegister_activation_key", "body/div[@id='eyebrow']/div[1]/ul/li[1]/div/ul/li[4]/a[@innertext='register activation key']", 30000, null, "e8169ab3-b9b5-446a-92b8-a572c34f8398");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2f8413b4-f347-43d1-9051-da2b02e6b5a8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2f8413b4-f347-43d1-9051-da2b02e6b5a8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ATagRegister_activation_key item.
            /// </summary>
            [RepositoryItem("e8169ab3-b9b5-446a-92b8-a572c34f8398")]
            public virtual Ranorex.ATag ATagRegister_activation_key
            {
                get
                {
                    return _atagregister_activation_keyInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagRegister_activation_key item info.
            /// </summary>
            [RepositoryItemInfo("e8169ab3-b9b5-446a-92b8-a572c34f8398")]
            public virtual RepoItemInfo ATagRegister_activation_keyInfo
            {
                get
                {
                    return _atagregister_activation_keyInfo;
                }
            }
        }

        /// <summary>
        /// The WebDocumentLynda_com_Online_TraininAppFolder folder.
        /// </summary>
        [RepositoryFolder("d9e81a5f-7c78-49b4-8bc7-7a27035de5d3")]
        public partial class WebDocumentLynda_com_Online_TraininAppFolder : RepoGenBaseFolder
        {
            repoActivationKeyFolders.SomeTableTagFolder _sometabletag;
            RepoItemInfo _selfInfo;
            RepoItemInfo _selecttagddlregselectInfo;

            /// <summary>
            /// Creates a new WebDocumentLynda_com_Online_Trainin  folder.
            /// </summary>
            public WebDocumentLynda_com_Online_TraininAppFolder(RepoGenBaseFolder parentFolder) :
                    base("WebDocumentLynda_com_Online_Trainin", "/dom[@domain='release.lynda.com' and @caption~'^lynda\\.com\\ Online\\ Training']", parentFolder, 30000, false, "d9e81a5f-7c78-49b4-8bc7-7a27035de5d3")
            {
                _sometabletag = new repoActivationKeyFolders.SomeTableTagFolder(this);
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "d9e81a5f-7c78-49b4-8bc7-7a27035de5d3");
                _selecttagddlregselectInfo = new RepoItemInfo(this, "SelectTagDdlRegSelect", "body/div[5]/div[2]/div[1]/p/select[@id='ddlRegSelect']", 30000, null, "36d44d20-819e-486a-826e-69263c84539f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d9e81a5f-7c78-49b4-8bc7-7a27035de5d3")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d9e81a5f-7c78-49b4-8bc7-7a27035de5d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectTagDdlRegSelect item.
            /// </summary>
            [RepositoryItem("36d44d20-819e-486a-826e-69263c84539f")]
            public virtual Ranorex.SelectTag SelectTagDdlRegSelect
            {
                get
                {
                    return _selecttagddlregselectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectTagDdlRegSelect item info.
            /// </summary>
            [RepositoryItemInfo("36d44d20-819e-486a-826e-69263c84539f")]
            public virtual RepoItemInfo SelectTagDdlRegSelectInfo
            {
                get
                {
                    return _selecttagddlregselectInfo;
                }
            }

            /// <summary>
            /// The SomeTableTag folder.
            /// </summary>
            [RepositoryFolder("07f8e120-cf8c-4850-adab-ca77e26d81cf")]
            public virtual repoActivationKeyFolders.SomeTableTagFolder SomeTableTag
            {
                get { return _sometabletag; }
            }
        }

        /// <summary>
        /// The SomeTableTagFolder folder.
        /// </summary>
        [RepositoryFolder("07f8e120-cf8c-4850-adab-ca77e26d81cf")]
        public partial class SomeTableTagFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _selecttagcountryInfo;
            RepoItemInfo _inputtagtxtactivationkeyInfo;
            RepoItemInfo _inputtagtxtfirstnameInfo;

            /// <summary>
            /// Creates a new SomeTableTag  folder.
            /// </summary>
            public SomeTableTagFolder(RepoGenBaseFolder parentFolder) :
                    base("SomeTableTag", "body/div[5]/div[2]/div[@id='divSpecialOffer']/div[@id='newuserform']/div[@id='divNewUser']/table", parentFolder, 30000, false, "07f8e120-cf8c-4850-adab-ca77e26d81cf")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "07f8e120-cf8c-4850-adab-ca77e26d81cf");
                _selecttagcountryInfo = new RepoItemInfo(this, "SelectTagCountry", "tbody/tr[1]/td/select[@id='Country']", 30000, null, "568ed8f2-5283-49f0-9308-234db27bfacd");
                _inputtagtxtactivationkeyInfo = new RepoItemInfo(this, "InputTagTxtActivationKey", "tbody/tr[2]/td/input[@id='txtActivationKey']", 30000, null, "ae2d2237-29ef-415a-a359-0a9e244586b2");
                _inputtagtxtfirstnameInfo = new RepoItemInfo(this, "InputTagTxtFirstName", "tbody/tr[3]/td/input[@id='txtFirstName']", 30000, null, "0a04623e-a809-4f72-a3ec-fc56fc7e1298");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("07f8e120-cf8c-4850-adab-ca77e26d81cf")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("07f8e120-cf8c-4850-adab-ca77e26d81cf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SelectTagCountry item.
            /// </summary>
            [RepositoryItem("568ed8f2-5283-49f0-9308-234db27bfacd")]
            public virtual Ranorex.SelectTag SelectTagCountry
            {
                get
                {
                    return _selecttagcountryInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The SelectTagCountry item info.
            /// </summary>
            [RepositoryItemInfo("568ed8f2-5283-49f0-9308-234db27bfacd")]
            public virtual RepoItemInfo SelectTagCountryInfo
            {
                get
                {
                    return _selecttagcountryInfo;
                }
            }

            /// <summary>
            /// The InputTagTxtActivationKey item.
            /// </summary>
            [RepositoryItem("ae2d2237-29ef-415a-a359-0a9e244586b2")]
            public virtual Ranorex.InputTag InputTagTxtActivationKey
            {
                get
                {
                    return _inputtagtxtactivationkeyInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagTxtActivationKey item info.
            /// </summary>
            [RepositoryItemInfo("ae2d2237-29ef-415a-a359-0a9e244586b2")]
            public virtual RepoItemInfo InputTagTxtActivationKeyInfo
            {
                get
                {
                    return _inputtagtxtactivationkeyInfo;
                }
            }

            /// <summary>
            /// The InputTagTxtFirstName item.
            /// </summary>
            [RepositoryItem("0a04623e-a809-4f72-a3ec-fc56fc7e1298")]
            public virtual Ranorex.InputTag InputTagTxtFirstName
            {
                get
                {
                    return _inputtagtxtfirstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagTxtFirstName item info.
            /// </summary>
            [RepositoryItemInfo("0a04623e-a809-4f72-a3ec-fc56fc7e1298")]
            public virtual RepoItemInfo InputTagTxtFirstNameInfo
            {
                get
                {
                    return _inputtagtxtfirstnameInfo;
                }
            }
        }

    }
}