///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Tests.General.Tests.MultiBrowser
{
    /// <summary>
    /// The class representing the MemberHomePage element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    [RepositoryFolder("12b2a37c-e9c1-4d56-a7d5-624b896a361e")]
    public partial class MemberHomePage : RepoGenBaseFolder
    {
        static MemberHomePage instance = new MemberHomePage();
        MemberHomePageFolders.MemberPageFolder _memberpage;

        /// <summary>
        /// Gets the singleton class instance representing the MemberHomePage element repository.
        /// </summary>
        [RepositoryFolder("12b2a37c-e9c1-4d56-a7d5-624b896a361e")]
        public static MemberHomePage Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MemberHomePage() 
            : base("MemberHomePage", "", null, 30000, false, "12b2a37c-e9c1-4d56-a7d5-624b896a361e", "./RepositoryImages\\MemberHomePage12b2a37c.rximgres")
        {
            _memberpage = new MemberHomePageFolders.MemberPageFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The MemberPage folder.
        /// </summary>
        [RepositoryFolder("a0cedce3-e83e-4a04-aed7-c772fef1be1d")]
        public virtual MemberHomePageFolders.MemberPageFolder MemberPage
        {
            get { return _memberpage; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    public partial class MemberHomePageFolders
    {
        /// <summary>
        /// The MemberPageFolder folder.
        /// </summary>
        [RepositoryFolder("a0cedce3-e83e-4a04-aed7-c772fef1be1d")]
        public partial class MemberPageFolder : RepoGenBaseFolder
        {
            RepoItemInfo _subscribelinkInfo;

            /// <summary>
            /// Creates a new MemberPage  folder.
            /// </summary>
            public MemberPageFolder(RepoGenBaseFolder parentFolder) :
                    base("MemberPage", "", parentFolder, 0, false, "a0cedce3-e83e-4a04-aed7-c772fef1be1d", "")
            {
                _subscribelinkInfo = new RepoItemInfo(this, "SubscribeLink", "/dom/body/div[@id='eyebrow']/div[1]/ul/li[2]/a[@innertext='subscribe']", 30000, null, "050b24e0-9350-46d6-96b9-e8eda1c76539");
            }

            /// <summary>
            /// The SubscribeLink item.
            /// </summary>
            [RepositoryItem("050b24e0-9350-46d6-96b9-e8eda1c76539")]
            public virtual Ranorex.ATag SubscribeLink
            {
                get
                {
                    return _subscribelinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SubscribeLink item info.
            /// </summary>
            [RepositoryItemInfo("050b24e0-9350-46d6-96b9-e8eda1c76539")]
            public virtual RepoItemInfo SubscribeLinkInfo
            {
                get
                {
                    return _subscribelinkInfo;
                }
            }
        }

    }
}