///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Browsers.IEBrowser
{
    /// <summary>
    /// The class representing the IE element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.2.3"), RepositoryFolder("20d858bd-54d3-486c-a6fb-bdd9ab5b016f")]
    public partial class IE : RepoGenBaseFolder
    {
        static IE instance = new IE();

        /// <summary>
        /// Gets the singleton class instance representing the IE element repository.
        /// </summary>
        [RepositoryFolder("20d858bd-54d3-486c-a6fb-bdd9ab5b016f")]
        public static IE Instance
        {
            get { return instance; }
        }

        IEFolders.FormAppFolder _form;
        IEFolders.DOMAppFolder _dom;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public IE() 
            : base("IE", "", null, 30000, false)
        {
            _form = new IEFolders.FormAppFolder(this);
            _dom = new IEFolders.DOMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Form folder.
        /// </summary>
        [RepositoryFolder("5bf07cb5-9605-4764-a654-0ea04402878e")]
        public virtual IEFolders.FormAppFolder Form
        {
            get { return _form; }
        }

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("ea9444db-7ca7-495f-9dfa-16ec93263cc5")]
        public virtual IEFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class IEFolders
    {
        /// <summary>
        /// The FormAppFolder folder.
        /// </summary>
        [RepositoryFolder("5bf07cb5-9605-4764-a654-0ea04402878e")]
        public partial class FormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _navigateeditboxInfo;
            RepoItemInfo _buttonbackInfo;
            RepoItemInfo _buttonforwardInfo;
            RepoItemInfo _menufileInfo;
            RepoItemInfo _menuhelpInfo;
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _windowInfo;

            /// <summary>
            /// Creates a new Form  folder.
            /// </summary>
            public FormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form", "/form[@class='IEFrame']", parentFolder, 30000, true, "5bf07cb5-9605-4764-a654-0ea04402878e")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "5bf07cb5-9605-4764-a654-0ea04402878e");
                _navigateeditboxInfo = new RepoItemInfo(this, "NavigateEditBox", "element[@class='WorkerW']/container/element[@controlid='41477']/text[@class='Edit']", 30000, null, "a8920685-d014-4a34-a858-940fde7c7f51");
                _buttonbackInfo = new RepoItemInfo(this, "ButtonBack", "element[@class='WorkerW']/container/element[@class='TravelBand']/toolbar/button[@text='Back']", 30000, null, "a5fe8c42-8d25-4fa6-9709-76dd3778cf01");
                _buttonforwardInfo = new RepoItemInfo(this, "ButtonForward", "element[@class='WorkerW']/container/element[@class='TravelBand']/toolbar/button[@text='Forward']", 30000, null, "6c9db020-7f88-4d88-a10b-b11afba914d6");
                _menufileInfo = new RepoItemInfo(this, "MenuFile", "element[@class='Frame Tab']/element/element/container/toolbar/button[@text='&File']", 30000, null, "fb631b50-307a-4ae5-95cf-424e49d7bbfa");
                _menuhelpInfo = new RepoItemInfo(this, "MenuHelp", "element[@class='Frame Tab']/element/element/container/toolbar/button[@text='&Help']", 30000, null, "4905f66e-5d6a-4417-9b59-5cdd0ef6342e");
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "element[@class='Client Caption']", 30000, null, "f38bb932-37cb-4f20-837e-59fc2c8ca211");
                _windowInfo = new RepoItemInfo(this, "Window", "", 30000, null, "781b97a2-b1da-4cf6-b702-779b4d5bbbb0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5bf07cb5-9605-4764-a654-0ea04402878e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5bf07cb5-9605-4764-a654-0ea04402878e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NavigateEditBox item.
            /// </summary>
            [RepositoryItem("a8920685-d014-4a34-a858-940fde7c7f51")]
            public virtual Ranorex.Text NavigateEditBox
            {
                get
                {
                    return _navigateeditboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NavigateEditBox item info.
            /// </summary>
            [RepositoryItemInfo("a8920685-d014-4a34-a858-940fde7c7f51")]
            public virtual RepoItemInfo NavigateEditBoxInfo
            {
                get
                {
                    return _navigateeditboxInfo;
                }
            }

            /// <summary>
            /// The ButtonBack item.
            /// </summary>
            [RepositoryItem("a5fe8c42-8d25-4fa6-9709-76dd3778cf01")]
            public virtual Ranorex.Button ButtonBack
            {
                get
                {
                    return _buttonbackInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonBack item info.
            /// </summary>
            [RepositoryItemInfo("a5fe8c42-8d25-4fa6-9709-76dd3778cf01")]
            public virtual RepoItemInfo ButtonBackInfo
            {
                get
                {
                    return _buttonbackInfo;
                }
            }

            /// <summary>
            /// The ButtonForward item.
            /// </summary>
            [RepositoryItem("6c9db020-7f88-4d88-a10b-b11afba914d6")]
            public virtual Ranorex.Button ButtonForward
            {
                get
                {
                    return _buttonforwardInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonForward item info.
            /// </summary>
            [RepositoryItemInfo("6c9db020-7f88-4d88-a10b-b11afba914d6")]
            public virtual RepoItemInfo ButtonForwardInfo
            {
                get
                {
                    return _buttonforwardInfo;
                }
            }

            /// <summary>
            /// The MenuFile item.
            /// </summary>
            [RepositoryItem("fb631b50-307a-4ae5-95cf-424e49d7bbfa")]
            public virtual Ranorex.Button MenuFile
            {
                get
                {
                    return _menufileInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MenuFile item info.
            /// </summary>
            [RepositoryItemInfo("fb631b50-307a-4ae5-95cf-424e49d7bbfa")]
            public virtual RepoItemInfo MenuFileInfo
            {
                get
                {
                    return _menufileInfo;
                }
            }

            /// <summary>
            /// The MenuHelp item.
            /// </summary>
            [RepositoryItem("4905f66e-5d6a-4417-9b59-5cdd0ef6342e")]
            public virtual Ranorex.Button MenuHelp
            {
                get
                {
                    return _menuhelpInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MenuHelp item info.
            /// </summary>
            [RepositoryItemInfo("4905f66e-5d6a-4417-9b59-5cdd0ef6342e")]
            public virtual RepoItemInfo MenuHelpInfo
            {
                get
                {
                    return _menuhelpInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("f38bb932-37cb-4f20-837e-59fc2c8ca211")]
            public virtual Ranorex.Unknown TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("f38bb932-37cb-4f20-837e-59fc2c8ca211")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The Window item.
            /// </summary>
            [RepositoryItem("781b97a2-b1da-4cf6-b702-779b4d5bbbb0")]
            public virtual Ranorex.Form Window
            {
                get
                {
                    return _windowInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Window item info.
            /// </summary>
            [RepositoryItemInfo("781b97a2-b1da-4cf6-b702-779b4d5bbbb0")]
            public virtual RepoItemInfo WindowInfo
            {
                get
                {
                    return _windowInfo;
                }
            }
        }

        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("ea9444db-7ca7-495f-9dfa-16ec93263cc5")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _webpageInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "ea9444db-7ca7-495f-9dfa-16ec93263cc5")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "ea9444db-7ca7-495f-9dfa-16ec93263cc5");
                _webpageInfo = new RepoItemInfo(this, "WebPage", "", 30000, null, "38bef810-ac24-4f45-9da5-f630e98feebc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ea9444db-7ca7-495f-9dfa-16ec93263cc5")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ea9444db-7ca7-495f-9dfa-16ec93263cc5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WebPage item.
            /// </summary>
            [RepositoryItem("38bef810-ac24-4f45-9da5-f630e98feebc")]
            public virtual Ranorex.WebDocument WebPage
            {
                get
                {
                    return _webpageInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The WebPage item info.
            /// </summary>
            [RepositoryItemInfo("38bef810-ac24-4f45-9da5-f630e98feebc")]
            public virtual RepoItemInfo WebPageInfo
            {
                get
                {
                    return _webpageInfo;
                }
            }
        }

    }
}