///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConsumerPagesMain.RegStep1
{
    /// <summary>
    /// The class representing the RegPageStep1Repo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    [RepositoryFolder("742ba02d-1b46-4948-9c3b-649792e2d609")]
    public partial class RegPageStep1Repo : RepoGenBaseFolder
    {
        static RegPageStep1Repo instance = new RegPageStep1Repo();
        RegPageStep1RepoFolders.DOMAppFolder _dom;

        /// <summary>
        /// Gets the singleton class instance representing the RegPageStep1Repo element repository.
        /// </summary>
        [RepositoryFolder("742ba02d-1b46-4948-9c3b-649792e2d609")]
        public static RegPageStep1Repo Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RegPageStep1Repo() 
            : base("RegPageStep1Repo", "", null, 30000, false, "742ba02d-1b46-4948-9c3b-649792e2d609", "./RepositoryImages\\RegPageStep1Repo742ba02d.rximgres")
        {
            _dom = new RegPageStep1RepoFolders.DOMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("89597d3b-6b55-44a6-aaa5-914eedf6a09b")]
        public virtual RegPageStep1RepoFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    public partial class RegPageStep1RepoFolders
    {
        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("89597d3b-6b55-44a6-aaa5-914eedf6a09b")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _continuebuttoninputInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "89597d3b-6b55-44a6-aaa5-914eedf6a09b", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "89597d3b-6b55-44a6-aaa5-914eedf6a09b");
                _continuebuttoninputInfo = new RepoItemInfo(this, "ContinueButtonInput", "body/div[1]/div[2]/form/fieldset/div[1]/table/tbody/tr[8]/td[2]/input[@id='btnContinue']", 30000, null, "0aac29bb-151d-4400-a8e8-8fea03c1cebe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("89597d3b-6b55-44a6-aaa5-914eedf6a09b")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("89597d3b-6b55-44a6-aaa5-914eedf6a09b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContinueButtonInput item.
            /// </summary>
            [RepositoryItem("0aac29bb-151d-4400-a8e8-8fea03c1cebe")]
            public virtual Ranorex.InputTag ContinueButtonInput
            {
                get
                {
                    return _continuebuttoninputInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ContinueButtonInput item info.
            /// </summary>
            [RepositoryItemInfo("0aac29bb-151d-4400-a8e8-8fea03c1cebe")]
            public virtual RepoItemInfo ContinueButtonInputInfo
            {
                get
                {
                    return _continuebuttoninputInfo;
                }
            }
        }

    }
}