///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ConsumerPagesAbstract.LyndaHeaderFooterPage3
{
    /// <summary>
    /// The class representing the HeaderRepo element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.2.3"), RepositoryFolder("1baeb281-0703-4776-ad8e-348e00fa0997")]
    public partial class HeaderRepo : RepoGenBaseFolder
    {
        static HeaderRepo instance = new HeaderRepo();

        /// <summary>
        /// Gets the singleton class instance representing the HeaderRepo element repository.
        /// </summary>
        [RepositoryFolder("1baeb281-0703-4776-ad8e-348e00fa0997")]
        public static HeaderRepo Instance
        {
            get { return instance; }
        }

        HeaderRepoFolders.DOMAppFolder _dom;

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public HeaderRepo() 
            : base("HeaderRepo", "", null, 30000, false)
        {
            _dom = new HeaderRepoFolders.DOMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("6683bd48-49ee-4212-8ab2-938e09fb7f27")]
        public virtual HeaderRepoFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    public partial class HeaderRepoFolders
    {
        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("6683bd48-49ee-4212-8ab2-938e09fb7f27")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _logoutInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "6683bd48-49ee-4212-8ab2-938e09fb7f27")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "6683bd48-49ee-4212-8ab2-938e09fb7f27");
                _logoutInfo = new RepoItemInfo(this, "LogOut", "body/div[@id='eyebrow']/div[1]/ul/li[3]/a/strong[@innertext='log out']", 30000, null, "066500ea-d342-40f5-b455-413fb027b51d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("6683bd48-49ee-4212-8ab2-938e09fb7f27")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("6683bd48-49ee-4212-8ab2-938e09fb7f27")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogOut item.
            /// </summary>
            [RepositoryItem("066500ea-d342-40f5-b455-413fb027b51d")]
            public virtual Ranorex.StrongTag LogOut
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.StrongTag>(true);
                }
            }

            /// <summary>
            /// The LogOut item info.
            /// </summary>
            [RepositoryItemInfo("066500ea-d342-40f5-b455-413fb027b51d")]
            public virtual RepoItemInfo LogOutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }
        }

    }
}