///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Browsers.SafariBrowser
{
    /// <summary>
    /// The class representing the Safari element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    [RepositoryFolder("a4f3ebd6-bd34-4818-936b-6d0a7e3de81a")]
    public partial class Safari : RepoGenBaseFolder
    {
        static Safari instance = new Safari();
        SafariFolders.DOMAppFolder _dom;
        SafariFolders.FormAppFolder _form;

        /// <summary>
        /// Gets the singleton class instance representing the Safari element repository.
        /// </summary>
        [RepositoryFolder("a4f3ebd6-bd34-4818-936b-6d0a7e3de81a")]
        public static Safari Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Safari() 
            : base("Safari", "", null, 30000, false, "a4f3ebd6-bd34-4818-936b-6d0a7e3de81a", "./RepositoryImages\\Safaria4f3ebd6.rximgres")
        {
            _dom = new SafariFolders.DOMAppFolder(this);
            _form = new SafariFolders.FormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("a68b881b-e066-4a8b-b4f6-fc6e32cc5639")]
        public virtual SafariFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }

        /// <summary>
        /// The Form folder.
        /// </summary>
        [RepositoryFolder("fcbfcd12-4c7a-41b5-bab5-a2655acc0c5a")]
        public virtual SafariFolders.FormAppFolder Form
        {
            get { return _form; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    public partial class SafariFolders
    {
        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("a68b881b-e066-4a8b-b4f6-fc6e32cc5639")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _webpageInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "a68b881b-e066-4a8b-b4f6-fc6e32cc5639", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "a68b881b-e066-4a8b-b4f6-fc6e32cc5639");
                _webpageInfo = new RepoItemInfo(this, "WebPage", "", 30000, null, "1b645d8d-7e90-46bd-87cd-1b358636d6dd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a68b881b-e066-4a8b-b4f6-fc6e32cc5639")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a68b881b-e066-4a8b-b4f6-fc6e32cc5639")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WebPage item.
            /// </summary>
            [RepositoryItem("1b645d8d-7e90-46bd-87cd-1b358636d6dd")]
            public virtual Ranorex.WebDocument WebPage
            {
                get
                {
                    return _webpageInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The WebPage item info.
            /// </summary>
            [RepositoryItemInfo("1b645d8d-7e90-46bd-87cd-1b358636d6dd")]
            public virtual RepoItemInfo WebPageInfo
            {
                get
                {
                    return _webpageInfo;
                }
            }
        }

        /// <summary>
        /// The FormAppFolder folder.
        /// </summary>
        [RepositoryFolder("fcbfcd12-4c7a-41b5-bab5-a2655acc0c5a")]
        public partial class FormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _navigateeditboxInfo;
            RepoItemInfo _navigateeditboxtextInfo;
            RepoItemInfo _titlebarInfo;

            /// <summary>
            /// Creates a new Form  folder.
            /// </summary>
            public FormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form", "/form[@processname='Safari']", parentFolder, 30000, true, "fcbfcd12-4c7a-41b5-bab5-a2655acc0c5a", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "fcbfcd12-4c7a-41b5-bab5-a2655acc0c5a");
                _navigateeditboxInfo = new RepoItemInfo(this, "NavigateEditBox", "element[@class='RootElement']/element[@class='SafariEdit']", 30000, null, "a78f072c-0064-439f-8667-e420d8b1964b");
                _navigateeditboxtextInfo = new RepoItemInfo(this, "NavigateEditBoxText", "element[@class='RootElement']/element[@class='SafariEdit']/element/element/container/container/container/text[@accessiblerole='Text']", 30000, null, "f1d72670-b050-4fc3-9812-964248d29b7c");
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "titlebar[@accessiblerole='TitleBar']", 30000, null, "3e5c24ba-69c1-44d5-bc45-f2550b6f764f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fcbfcd12-4c7a-41b5-bab5-a2655acc0c5a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fcbfcd12-4c7a-41b5-bab5-a2655acc0c5a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NavigateEditBox item.
            /// </summary>
            [RepositoryItem("a78f072c-0064-439f-8667-e420d8b1964b")]
            public virtual Ranorex.Unknown NavigateEditBox
            {
                get
                {
                    return _navigateeditboxInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The NavigateEditBox item info.
            /// </summary>
            [RepositoryItemInfo("a78f072c-0064-439f-8667-e420d8b1964b")]
            public virtual RepoItemInfo NavigateEditBoxInfo
            {
                get
                {
                    return _navigateeditboxInfo;
                }
            }

            /// <summary>
            /// The NavigateEditBoxText item.
            /// </summary>
            [RepositoryItem("f1d72670-b050-4fc3-9812-964248d29b7c")]
            public virtual Ranorex.Text NavigateEditBoxText
            {
                get
                {
                    return _navigateeditboxtextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The NavigateEditBoxText item info.
            /// </summary>
            [RepositoryItemInfo("f1d72670-b050-4fc3-9812-964248d29b7c")]
            public virtual RepoItemInfo NavigateEditBoxTextInfo
            {
                get
                {
                    return _navigateeditboxtextInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("3e5c24ba-69c1-44d5-bc45-f2550b6f764f")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("3e5c24ba-69c1-44d5-bc45-f2550b6f764f")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }
        }

    }
}