///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Browsers.FirefoxBrowser
{
    /// <summary>
    /// The class representing the Firefox element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    [RepositoryFolder("76c841d7-0ac5-4985-b102-a45cc6bbeb68")]
    public partial class Firefox : RepoGenBaseFolder
    {
        static Firefox instance = new Firefox();
        FirefoxFolders.FormAppFolder _form;
        FirefoxFolders.DOMAppFolder _dom;

        /// <summary>
        /// Gets the singleton class instance representing the Firefox element repository.
        /// </summary>
        [RepositoryFolder("76c841d7-0ac5-4985-b102-a45cc6bbeb68")]
        public static Firefox Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Firefox() 
            : base("Firefox", "", null, 30000, false, "76c841d7-0ac5-4985-b102-a45cc6bbeb68", "./RepositoryImages\\Firefox76c841d7.rximgres")
        {
            _form = new FirefoxFolders.FormAppFolder(this);
            _dom = new FirefoxFolders.DOMAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Form folder.
        /// </summary>
        [RepositoryFolder("1a43965b-5ca0-43b4-b128-7d9e666d98ff")]
        public virtual FirefoxFolders.FormAppFolder Form
        {
            get { return _form; }
        }

        /// <summary>
        /// The DOM folder.
        /// </summary>
        [RepositoryFolder("daefb408-00fb-47dd-a6ab-a1b9e297f4a7")]
        public virtual FirefoxFolders.DOMAppFolder DOM
        {
            get { return _dom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "3.3.0")]
    public partial class FirefoxFolders
    {
        /// <summary>
        /// The FormAppFolder folder.
        /// </summary>
        [RepositoryFolder("1a43965b-5ca0-43b4-b128-7d9e666d98ff")]
        public partial class FormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _navigateeditboxInfo;
            RepoItemInfo _buttonbackInfo;
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _windowInfo;

            /// <summary>
            /// Creates a new Form  folder.
            /// </summary>
            public FormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form", "/form[@class='MozillaWindowClass']", parentFolder, 30000, true, "1a43965b-5ca0-43b4-b128-7d9e666d98ff", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "1a43965b-5ca0-43b4-b128-7d9e666d98ff");
                _navigateeditboxInfo = new RepoItemInfo(this, "NavigateEditBox", "container[@accessiblerole='PropertyPage']/toolbar[@accessiblename='Navigation Toolbar']/combobox[@accessiblename='Go to a Website']", 30000, null, "0535d943-7b3b-4f00-9b16-79a1cc1a9464");
                _buttonbackInfo = new RepoItemInfo(this, "ButtonBack", "container[@accessiblerole='PropertyPage']/toolbar[@accessiblename='Navigation Toolbar']/button[@accessiblename='Back']", 30000, null, "46b3d8f2-3ffa-4b04-bd89-52096725d18f");
                _titlebarInfo = new RepoItemInfo(this, "TitleBar", "titlebar[@accessiblerole='TitleBar']", 30000, null, "1441865f-b978-4565-91ad-90beac40b672");
                _windowInfo = new RepoItemInfo(this, "Window", "", 30000, null, "c50aabf4-60a8-486a-89f0-18dc37598530");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1a43965b-5ca0-43b4-b128-7d9e666d98ff")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1a43965b-5ca0-43b4-b128-7d9e666d98ff")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NavigateEditBox item.
            /// </summary>
            [RepositoryItem("0535d943-7b3b-4f00-9b16-79a1cc1a9464")]
            public virtual Ranorex.ComboBox NavigateEditBox
            {
                get
                {
                    return _navigateeditboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The NavigateEditBox item info.
            /// </summary>
            [RepositoryItemInfo("0535d943-7b3b-4f00-9b16-79a1cc1a9464")]
            public virtual RepoItemInfo NavigateEditBoxInfo
            {
                get
                {
                    return _navigateeditboxInfo;
                }
            }

            /// <summary>
            /// The ButtonBack item.
            /// </summary>
            [RepositoryItem("46b3d8f2-3ffa-4b04-bd89-52096725d18f")]
            public virtual Ranorex.Button ButtonBack
            {
                get
                {
                    return _buttonbackInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonBack item info.
            /// </summary>
            [RepositoryItemInfo("46b3d8f2-3ffa-4b04-bd89-52096725d18f")]
            public virtual RepoItemInfo ButtonBackInfo
            {
                get
                {
                    return _buttonbackInfo;
                }
            }

            /// <summary>
            /// The TitleBar item.
            /// </summary>
            [RepositoryItem("1441865f-b978-4565-91ad-90beac40b672")]
            public virtual Ranorex.TitleBar TitleBar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The TitleBar item info.
            /// </summary>
            [RepositoryItemInfo("1441865f-b978-4565-91ad-90beac40b672")]
            public virtual RepoItemInfo TitleBarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The Window item.
            /// </summary>
            [RepositoryItem("c50aabf4-60a8-486a-89f0-18dc37598530")]
            public virtual Ranorex.Form Window
            {
                get
                {
                    return _windowInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Window item info.
            /// </summary>
            [RepositoryItemInfo("c50aabf4-60a8-486a-89f0-18dc37598530")]
            public virtual RepoItemInfo WindowInfo
            {
                get
                {
                    return _windowInfo;
                }
            }
        }

        /// <summary>
        /// The DOMAppFolder folder.
        /// </summary>
        [RepositoryFolder("daefb408-00fb-47dd-a6ab-a1b9e297f4a7")]
        public partial class DOMAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _selfInfo;
            RepoItemInfo _webpageInfo;

            /// <summary>
            /// Creates a new DOM  folder.
            /// </summary>
            public DOMAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DOM", "/dom", parentFolder, 30000, false, "daefb408-00fb-47dd-a6ab-a1b9e297f4a7", "")
            {
                _selfInfo = new RepoItemInfo(this, "Self", "", 0, null, "daefb408-00fb-47dd-a6ab-a1b9e297f4a7");
                _webpageInfo = new RepoItemInfo(this, "WebPage", "", 30000, null, "40522d18-2021-417a-9d52-1b1a82d39a74");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("daefb408-00fb-47dd-a6ab-a1b9e297f4a7")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("daefb408-00fb-47dd-a6ab-a1b9e297f4a7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The WebPage item.
            /// </summary>
            [RepositoryItem("40522d18-2021-417a-9d52-1b1a82d39a74")]
            public virtual Ranorex.WebDocument WebPage
            {
                get
                {
                    return _webpageInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The WebPage item info.
            /// </summary>
            [RepositoryItemInfo("40522d18-2021-417a-9d52-1b1a82d39a74")]
            public virtual RepoItemInfo WebPageInfo
            {
                get
                {
                    return _webpageInfo;
                }
            }
        }

    }
}